### ISSUE TITLE
Web editor don't work for me

### ISSUE THREAD

**Issue by titanium63** [lucko/LuckPermsWeb#10]
Hello,
When i click on the link after have do this command lp group <group> editor, the web page is empty. there is just a sympbol of luckperms. Yesterday it worked.

**Comment by lucko** [comment]
You need to clear your browsers cache.

Try using Ctrl + F5.

**Comment by titanium63** [comment]
it's not working. i have exactly that:
- logo luckperms
- LuckPerms Web Permissions Editor
- To start a new editor session, please use
- /lp user <user> editor
- /lp group <group> editor

**Comment by lucko** [comment]
Yes - I know. My previous reply still applies though.

> You need to clear your browsers cache.

**Comment by titanium63** [comment]
You are right but the firt clear don't work and the second it's good. 
Sorry for my stupid issue ^^
Thank you
