### ISSUE TITLE
[v2] Copy to clipboard for apply edits command

### ISSUE THREAD

**Issue by TheOnlyMaldred** [lucko/LuckPermsWeb#101]
Please bring back the "Click-to-copy" button from the old editor

![image](https://user-images.githubusercontent.com/43855785/69833014-9d780a80-11ee-11ea-8ef3-fed077153515.png)

![image](https://user-images.githubusercontent.com/43855785/69833028-b5e82500-11ee-11ea-9450-049995f91484.png)

**Comment by BrainStone** [comment]
The old one used clipboard.js @Turbotailz. Super easy to use (in case you don’t know it)

**Comment by Turbotailz** [comment]
Added in 654e493940db73caec7c6b5cfa9382b69bbcc3d0
