### ISSUE TITLE
[v2] Web Editor Freezes with Yellow M Symbol

### ISSUE THREAD

**Issue by VanillaChan6571** [lucko/LuckPermsWeb#102]
When removing group permissions from groups, The group has a yellow M Symbol next to it and doesn't remove the perm you clicked on and instead freezing the web editor causing you to reload and you can't even interact with any other group or user after this M symbol not even save button works.

This does NOT Occur when deleting User Perms.

**Comment by Turbotailz** [comment]
Please post a link to your editor.

**Comment by Andre601** [comment]
Could you check your browser console for any errors appearing and providing a screenshot of it?

**Comment by VanillaChan6571** [comment]
@Turbotailz You want my editor link? 
@Andre601 In console It says TypeError: "n is undefined"

**Comment by Turbotailz** [comment]
> You want my editor link?
That's what I asked, yes.

**Comment by VanillaChan6571** [comment]
@Turbotailz https://editor.luckperms.net/CoU8Hc4qmo

**Comment by Turbotailz** [comment]
Thanks. I will take a look at this when I can.

**Comment by VanillaChan6571** [comment]
Don't they expire?

**Comment by Turbotailz** [comment]
After a week. I should be able to take a look on Sunday at the earliest. If it does expire I will ask for another.

**Comment by Turbotailz** [comment]
Maybe I don't understand the issue but I can't seem to reproduce. Can you tell me exactly the steps you are taking to cause this error?

**Comment by Ppandamc** [comment]
https://editor.luckperms.net/oeckOAfF05

Whenever trying to delete a permission from default group freezes with M highlighted next to group.

**Comment by BrainStone** [comment]
Can you show us a screenshot?

**Comment by Turbotailz** [comment]
I was able to delete all permissions from both groups without any issues.

Perhaps it is a browser issue? What browser are you using @Ppandamc ?

**Comment by Turbotailz** [comment]
I can confirm this is a bug with Firefox and Safari. Will hopefully have a fix this weekend. In the meantime, you should use Chrome if you want to use the editor.

**Comment by Turbotailz** [comment]
I think this may have been inadvertently fixed in some recent commits to the project. I can no longer reproduce the bug in Firefox.

**Comment by Turbotailz** [comment]
@VanillaChan6571 @Ppandamc can you please confirm whether this bug is still present in the web editor?

**Comment by Ppandamc** [comment]
> @VanillaChan6571 @Ppandamc can you please confirm whether this bug is still present in the web editor?

it is working 100% now

**Comment by Turbotailz** [comment]
Kind of annoying, as I have no idea how I fixed it, but good to know 😛 thank you.
