### ISSUE TITLE
Epic spawners does not cooperate with luck perms? version: 5.0.12

### ISSUE THREAD

**Issue by partridge420x** [lucko/LuckPermsWeb#107]
Hello, I am trying to use Epic Spawners on a bungeecord network deployment through MariaDB (luckperms db), and it seems that permissions arent applying. 
I will provide a video below, along with screenshot of the permission applied

There are no console errors of any kind. Configs have been double checked several times. Epic furnaces works just fine. but spawners still seems to have a problem

The current test is on a freshly installed server. only plugins are epic spawners, and luck perms

Video: https://www.youtube.com/watch?v=uwOrHfw4tJc&feature=youtu.be
Verbose: https://luckperms.net/verbose/#KevGfdYnZD

Luckperms version: 5.0.12

openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

Affected Plugins
(ES) EpicSpawners
Minecraft Version
1.12.2
Plugin Version
6.1.15
Output of /songoda diag
[17:35:44 INFO]: Songoda Diagnostics Information
[17:35:44 INFO]:
[17:35:44 INFO]: Plugins:
[17:35:44 INFO]: EpicSpawners (6.1.15 Core 2.2.11)
[17:35:44 INFO]:
[17:35:44 INFO]: Server Version: git-Paper-1618 (MC: 1.12.2)
[17:35:44 INFO]: NMS: PAPER v1_12_R1
[17:35:44 INFO]: Operating System: Linux
[17:35:44 INFO]: Allocated Memory: 989Mb
[17:35:44 INFO]: Online Players: 2
[17:35:44 INFO]: TPS from last 1m, 5m, 15m: 19.99, 19.99, 19.98

also added note. the permission is there plugin side to get that out of the way: 
![image](https://user-images.githubusercontent.com/26298829/70367406-8af47580-186d-11ea-8db9-5fca5c94e361.png)

**Comment by Turbotailz** [comment]
Wrong repository, you want [lucko/LuckPerms](https://github.com/lucko/LuckPerms)

**Comment by partridge420x** [comment]
closed, Re opened on correct page. my bad didnt notice i was on the wrong github
