### ISSUE TITLE
Make it more clear that "Contexts" is where you would add a server/world contexts

### ISSUE THREAD

**Issue by SmartHosting** [lucko/LuckPermsWeb#108]
Hey I am using luckperms in an very bigg netwerk I want it to have easy setting permissions to 1 world / server cause rn I need to do that with commands files is not possible cause I am using database (mysql)

**Comment by BrainStone** [comment]
You can set the server and world context in the webeditor. I don’t understand your issue.

**Comment by SmartHosting** [comment]
How?? Ik can't do it anymore since they beta webeditor the old one met me do that

**Comment by Turbotailz** [comment]
It seems that this isn't terribly obvious to a lot of people and I will attempt to improve that, but the server and world contexts are now merged with the contexts field:

![Adding contexts with editor v2](https://i.imgur.com/kNUHkyS.gif)

**Comment by SmartHosting** [comment]
Just found out I messed some around with it it is working right now but also sort of not… you can't change the value that would be nice you can create a value also recreate by deleting it first but like in the old editor just clicking on it to change it would be nice

**Comment by SmartHosting** [comment]
and yes you are true xD I didn't notice It is the context field you have place there set them under each other instead of 1

**Comment by Turbotailz** [comment]
> you can't change the value

This is known and will be fixed at some point. Remember it is still in a beta state so there are a lot of missing features yet to be added.

> (or seperate them)

Luck has specifically said he doesn't want them separated anymore, which is why they are combined now.

**Comment by Andre601** [comment]
Maybe add a small text like "Use 'world' for the 'world=' and 'server' for the 'server=' context respecively in the key field."
I mean it's not like there wouldn't be enough space to do that /s
![image](https://user-images.githubusercontent.com/11576465/70869874-7c087400-1f8d-11ea-9c2c-dce45a9d02b1.png)

**Comment by Turbotailz** [comment]
I was going to make `key` a drop down menu with known context keys and the ability to add a custom context key as well.

**Comment by Andre601** [comment]
I would have a suggestion for the context field:
Have two lines pre-defined with "server" and "world" as keys, where the user could add server and world name and under those the empty key-value pair.

Something like this:
```
Imagine this being the context menu

------------------------
| Context (0)        x |
|----------------------|
| server   |           |
| world    |           |
| <key>    | <value>   |
------------------------
```
