### ISSUE TITLE
LuckPerms Web Editor won't load

### ISSUE THREAD

**Issue by RamboOne2** [lucko/LuckPermsWeb#109]
I tried posting this on the LuckPerms forum, and they recommended I posted here as well, so here goes:

I have a strange issue with the Web Editor.

When I initially downloaded the plugin a few days ago, I was able to use the "/lp editor" command, click the link, and use the Web Editor without any issues.

However, after that initial day or two of using the Web Editor, I have had nothing but issues. First I was unable to get a link, as it would give me the in-game message of "Preparing a new editor session. Please wait...", but never actually provide a link. Today it does give me a link but refuses to work on Chrome. First I got it to open on Chrome, but it wouldn't save the changes and provide a link; it just kept loading. I then refreshed and got the same issue of it claiming it couldn't load the Web Editor. I tried making one or two new links, none of them worked. I then tried opening the links in Firefox, and it worked once, and I could save the changes, but that also only worked once. Now I keep getting the "Loading error", no matter what I do.

Please help!

![LuckPerms Error](https://user-images.githubusercontent.com/52075840/70392573-ab454100-19e1-11ea-902c-4dc6be538ac4.PNG)

![LuckPerms Error2](https://user-images.githubusercontent.com/52075840/70392575-aed8c800-19e1-11ea-8f1c-7ebf1d2a4eab.PNG)

**Comment by Turbotailz** [comment]
You might want to try updating LuckPerms to version 5 which comes with version 2 of the web editor, it might fix any issues you are having here.

Though this problem might be due to CloudFlare and nothing wrong with the editor itself.
