### ISSUE TITLE
webstie doesnt respond after deleting a permission

### ISSUE THREAD

**Issue by Yuval270** [lucko/LuckPermsWeb#111]
agian, title says it all

**Comment by BrainStone** [comment]
In #110 you said you can’t delete them. What is it now?

**Comment by Turbotailz** [comment]
These have to be the most vague issues I've ever seen.

Mind sharing a bit more info? Maybe a link to your editor session? How can you expect us to have any idea on the problem when all you say is "title says it all"?

**Comment by Turbotailz** [comment]
Duplicate of #102
