### ISSUE TITLE
Suggestion - Editable Suffix / Prefix after created

### ISSUE THREAD

**Issue by EnergitCZ** [lucko/LuckPermsWeb#114]

**Comment by Andre601** [comment]
.....what?

**Comment by Turbotailz** [comment]
You can edit the prefixes and suffixes in the web editor. I'm not sure what you're trying to suggest here.

**Comment by Andre601** [comment]
Obviously nothing according to the content of his issue. ;)

**Comment by Turbotailz** [comment]
One month on and still no info. I will close this now.
