### ISSUE TITLE
[bug] Whenever I put permissions in then I save they dont work

### ISSUE THREAD

**Issue by Clixty** [lucko/LuckPermsWeb#117]
Sometimes whenever I put permissions in, they do work and they do not let the person do the commands/interact with it. And they are the correct permissions.

**Comment by Turbotailz** [comment]
This isn't an issue with the web editor but more a misunderstanding of which permissions are actually correct. I would make use of [Verbose mode](https://github.com/lucko/LuckPerms/wiki/Verbose) to see what permissions are actually being checked when the commands are being ran.
