### ISSUE TITLE
Permission Nodes

### ISSUE THREAD

**Issue by Bestpa** [lucko/LuckPermsWeb#120]
On the web editor only the permission nodes for bungee show, Is there any way to fix this?

**Comment by Andre601** [comment]
Use the command on the spigot server with `/lp editor`

**Comment by Bestpa** [comment]
This doesn't work, There is no such command as /lp, only /lpb

**Comment by Andre601** [comment]
Then you messed something up as the web editor is only accessed through `/lp editor`

**Comment by BrainStone** [comment]
Not correct. You can run `/lpb editor` as well.

But that indicates that you don't have LP installed on all your backend servers.  
Which you need to do if you want LP to handle permissions on those servers.

**Comment by Turbotailz** [comment]
If `/lp` doesn't exist, then you haven't installed LuckPerms on your backend server(s), so you need to do that to run a network properly. See the wiki page: https://github.com/lucko/LuckPerms/wiki/Network-Installation
