### ISSUE TITLE
Autofill in Web Editor

### ISSUE THREAD

**Issue by bartyrealms** [lucko/LuckPermsWeb#121]
Currently, the web editor will add suggestions regardless if you type anything. This is inherently dangerous because if you type in a permission, hit enter, then hit enter again, it will immediately put in *, since * is the first permission suggested.

![image](https://user-images.githubusercontent.com/42015460/71645577-6d69ce80-2ca8-11ea-8d5c-27517d91dfa0.png)

This makes it very easy to mistakenly give groups the * permission.

Some suggestions for fixing this:

1. Add a timer after entering in a permission before accepting another "enter" key input. This would make it so you do not accidentally add a permission on top of what you were doing.

2. Remove suggested permissions if you have not typed anything.

3. At least add a toggle for disabling suggested permissions if you have not typed anything.

Example of this issue in action:
https://i.gyazo.com/4820781a0cc1a48cf3755651dead8289.mp4

**Comment by Andre601** [comment]
Who just presses enter right away?
Do you usually not just type the perm, select it and THEN press enter?

**Comment by bartyrealms** [comment]
> Who just presses enter right away?
> Do you usually not just type the perm, select it and THEN press enter?

The issue is that the * permission is the first to autofill, and pressing enter at any point will add that permission, even if you didn't type anything. It is very easy to do after typing a list of permissions or even a single permission if you watch the video.

This is more of a QOL feature, so people don't accidentally destroy their server due to a simple mistake of accidentally pressing enter once.

**Comment by Turbotailz** [comment]
I have been trying to see why it is beneficial to have the autofill show without any input and can't really see any reason. So I will look into removing it until someone has begun typing.

**Comment by leasoncre** [comment]
i would also find it nicer if i cold edit the node before i hit the + button (currently you can't do that until it is in the full list, which is what i'd expect it to do as so as i hit enter anyway

PS. auto-fill suggestion: automatically highlight permission nodes already in the group's list, not just those you are currently adding. (#prevent duplicate add)

**Comment by Turbotailz** [comment]
> i would also find it nicer if i cold edit the node before i hit the + button
I am not sure exactly what you mean by this, could you please explain in more detail?

> automatically highlight permission nodes already in the group's list, not just those you are currently adding. (#prevent duplicate add)
I won't do this, as it is necessary to add duplicate permissions to a group/user with different contexts.

**Comment by leasoncre** [comment]
https://gyazo.com/7c9f447519448ca910e8f0393095358a.gif - i can't edit the node i just added to the add que

> > i would also find it nicer if i cold edit the node before i hit the + button
> I am not sure exactly what you mean by this, could you please explain in more detail?
https://gyazo.com/7c9f447519448ca910e8f0393095358a.gif i can't edit the node before clicking the + button, ie: if i wanted to - (negate) that node i'd have to type the whole thing, or add the node, then edit it in the main list. I know i can just delete and re-add it, or edit it after,, but it's just more tedious.

> > automatically highlight permission nodes already in the group's list, not just those you are currently adding. (#prevent duplicate add)
> I won't do this, as it is necessary to add duplicate permissions to a group/user with different contexts.
what? oh the key things i haven't used yet. I was thinking if the base node is already added (in the mian list, ignoring keys) highlight it in the suggestion list, like it does when you add multiple nodes to the box in the above gif. just makes it easier to see since the main list isn't sorted at all.

**Comment by Turbotailz** [comment]
> if i wanted to - (negate) that node

FYI - typing `-` before a permission node does *not* negate it. That's what the `true` / `false` values are for.

The library I've used for the select menu does not allow for editing the values inline. I don't believe it justifies forking the project just to add that feature when the user can either delete and enter the permission node again, or add the node and edit in within the list easily.
