### ISSUE TITLE
Allow deletion of groups

### ISSUE THREAD

**Issue by JustAPieOP** [lucko/LuckPermsWeb#122]
Can you make the editor can delete groups

**Comment by james090500** [comment]
is /lp deletegroup group really that difficult?

**Comment by Andre601** [comment]
> is `/lp deletegroup group` really that difficult?

This would be a QOL change for the editor imo.
I mean you could also ask "Is `/lp creategroup group` really that difficult?" too, since the editor now has the option to create groups.

**Comment by james090500** [comment]
> > is `/lp deletegroup group` really that difficult?
> 
> This would be a QOL change for the editor imo.
> I mean you could also ask "Is `/lp creategroup group` really that difficult?" too, since the editor now has the option to create groups.

Yeh that's my bad. I'm thinking of the old editor. If the new one has create group might as well add delete group

**Comment by JustAPieOP** [comment]
I am thinking of that. If the current editor has feature to create group, why don't you make a feature that allow users to delete groups

**Comment by BrainStone** [comment]
The reason is simple.  
That feature was (and still is) planned. But was simply forgotten to implement. And the maintainer of the webeditor currently doesn’t have time to add it.  
We are aware and will add it eventually. Though there’s no high priority for it.

**Comment by Turbotailz** [comment]
I simply forgot to add it in while I was developing it. I should have some time to make some updates to the editor soon. Sorry!

**Comment by Turbotailz** [comment]
Added in cd9598c977ec492c45c783c68fa14fdd038f79f1
