### ISSUE TITLE
CSS Issue

### ISSUE THREAD

**Issue by Dalton-West** [lucko/LuckPermsWeb#125]
I had an issue with the editor. The following classes may need editing .sorting-tabs & multiselect__content. I attached a screenshot of the bug. My mouse is hovered over the value sorter.
![luckperms_editor_bug](https://user-images.githubusercontent.com/6106010/71860618-7abbfa00-30a8-11ea-92f1-78d5473d153a.png)

**Comment by Turbotailz** [comment]
Ah looks like a z-index issue on smaller screens. Thanks.
