### ISSUE TITLE
Can't save parameters

### ISSUE THREAD

**Issue by AlexandreBouton** [lucko/LuckPermsWeb#127]
Hi there, 
When I am trying to moove someone in a group. To do that, I open the editor and I change the group in the line "group.default". When I want to save, I have an error on this line.

What can I do ? 

Ty !

**Comment by Andre601** [comment]
What "error"?

**Comment by AlexandreBouton** [comment]
"There was an error whilst saving user data for <player>"

**Comment by Turbotailz** [comment]
Console errors? You need to provide more info than this please.

**Comment by AlexandreBouton** [comment]
Well...

When I open the editor on my web browser, I set the line "group.default" in "group.newgroup".
Then, I click on save, on the top of the screen. I copy the link and I paste it into minecraft. At this moment, the error appears.

**Comment by Andre601** [comment]
Then please give us the error displayed (Take a screenshot)

**Comment by Turbotailz** [comment]
Does `newgroup` exist as a group?

**Comment by AlexandreBouton** [comment]
Oh, I have no player to test it and to send you, everybody disconncted... I send you the screenshot as soon as possible ! 

Yes, he does

**Comment by AlexandreBouton** [comment]
https://zupimages.net/viewer.php?id=20/03/orsy.png

Here is the screenshot !

**Comment by BrainStone** [comment]
Any errors in the console when that happens?

**Comment by AlexandreBouton** [comment]
The minecraft server is a daemon programm. How can I hook the console to give you this information ?

**Comment by BrainStone** [comment]
That’s something you should know. There’s so many different setups, it’s impossible to say. 

You could also check the log file.

**Comment by Turbotailz** [comment]
I'm going to say this is not an issue with the editor but more of a misconfiguration with your installation. If you are having more issues with LuckPerms, please consider joining our [Discord](https://discord.gg/luckperms) for further support.

Closing this for now.
