### ISSUE TITLE
Add copy button to permissions

### ISSUE THREAD

**Issue by iTz-MrAnonymous** [lucko/LuckPermsWeb#128]
copy the last entry made in the web editor when adding permissions.

**Comment by Tobi406** [comment]
What do you mean with that? Also a better place for that might be the [lucko/LuckPermsWeb](https://github.com/lucko/LuckPermsWeb) repository

**Comment by iTz-MrAnonymous** [comment]
Sorry, it didn't save correctly

**Comment by iTz-MrAnonymous** [comment]
Also, it would be nice to have a button where you can copy the permission node and context, etc.

**Comment by Turbotailz** [comment]
Uh, can you please explain in more detail? And a potential use case? I don't see how this is beneficial at all so I'd like to understand it a bit better.

**Comment by iTz-MrAnonymous** [comment]
The suggestion features here were two features that were apart of the last web editor version.
https://imgur.com/a/hP0zQvV
essentially when adding permission nodes via the web editor on the old version, it would copy the last entry made in the web editor (the section of the web editor I am referring to can be seen in the above image). So if you were adding a large number of permission nodes but all had the same context etc, you would only need to worry about changing the permission node, such make the whole process a lot faster.

https://imgur.com/a/kZZB33R
The button that is seen in this image, also made it the process of editing/adding permission nodes faster. If there was a permission node that had a particular context you wanted to copy, you would only need to press that button to copy everything.

**Comment by iTz-MrAnonymous** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/kZZB33R"  ><a href="//imgur.com/a/kZZB33R">ewsaagsdfsd</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by Turbotailz** [comment]
I forgot about the copy button to be honest. But you realise you can add multiple permissions to the input at the bottom? This might be be useful for you as you can add a lot of permissions with the same contexts, etc.

**Comment by iTz-MrAnonymous** [comment]
Whoops, my bad for not being aware of that.

In that case, the only thing I would suggest is maybe a copy button? Though that obviously isn't super important, it's just handy to have.
