### ISSUE TITLE
[SUGGESTION] Allow copying of webeditor server to server

### ISSUE THREAD

**Issue by EchocallingEarth** [lucko/LuckPermsWeb#129]
The request is to allow an owner who uses a test server and a production server to easily copy the LP permissions from one server to the other using the webeditor instead of copying the configs.

In theory, this could be done by clicking on a button on the webeditor which would then copy all entries and then using a similar button import them into the new server LP webeditor.

The buttons could be called export and import and when used they would make a snapshot of the data as a copy and just move it into the new server.

However, the owner or person making the changes would still need to save the permission and follow normal steps to ensure the information/permissions updated correctly.

**Comment by Andre601** [comment]
## First option: Actually export and import
1. On test server, run `/lp export <name>`
2. Take .json.tar generated and move it to your prod server
3. Use `/lp import <filename>`

## Second option: Editor
1. Open editor with `/lp editor` on test server
2. Press the save button.
3. Execute the generated command on Prod.

**Comment by Turbotailz** [comment]
This isn't really a job for the web editor and you should use the export/import method Andre mentioned above.
