### ISSUE TITLE
Improve group/user parent modifications

### ISSUE THREAD

**Issue by Dodison** [lucko/LuckPermsWeb#130]
It would have been nice if there would be a option so one could set the parent of a group after creating it. Without having to use the permission nodes. Same with e.g. the weight.

**Comment by Turbotailz** [comment]
Do you have any suggestions for how it should work? I can't think of anything easier than using permission nodes :stuck_out_tongue:

**Comment by Dodison** [comment]
A dropdown menu like in the creation menu.
