### ISSUE TITLE
Make adding perms to users

### ISSUE THREAD

**Issue by oliyase** [lucko/LuckPermsWeb#131]
I needing to add perms to users. You can make it with making the same folder as a tracks or groups and the same editor.

**Comment by BrainStone** [comment]
You can edit player permissions with it.  
Can you maybe elaborate what you mean? Maybe provide screenshots.

**Comment by Turbotailz** [comment]
Adding permissions to users has always been a feature of the editor. The user must be online to appear in the list. Otherwise I'm pretty sure you can run `/lp user <user> editor` to target a single user.

**Comment by Turbotailz** [comment]
Adding permissions to users has always been a feature of the editor. The user must be online to appear in the list. Otherwise I'm pretty sure you can run `/lp user <user> editor` to target a single user.
