### ISSUE TITLE
Update Context UI to allow for editing contexts inline

### ISSUE THREAD

**Issue by TechieBlort** [lucko/LuckPermsWeb#140]
I have been using the beta editor through the luck perms site for the past few weeks and have a few problems with it but want to note: I like change but certain type of things like this editor which is worse than the old one in my opinion. Don't get me wrong I like being able to add multiple permissions as much as the next guy but this just makes it bad. Here's why:
1. The permissions don't transfer over from other groups (IDK if this is a bug) and makes it annoying when your trying to add multiple permissions to multiple groups but for different servers and makes my life and possibly others worse than better.
2. You can't change context on mass or just in general. Once you add a context if it has an error like a space at the end of a key you are screwed unless you delete the permission's current context and re-add it and pray it's fixed. I propose the ability to edit these contexts after they are added so it takes out the extra step to have to redo it. This is fine if the error is just 1 or 2 permissions but on a much larger scale it's bad and can just get worse.

**Comment by Turbotailz** [comment]
I'm sorry you don't like the new version of the editor :/

Just want to clarify a couple of things:

- it is still a beta version, so of course there will be a few things that don't work as intended
- I'm not sure what you mean by "the permissions don't transfer over from other groups", can you elaborate more on this? This sounds like your inheritance isn't working? That is not an error of the web editor and more to do with how you have set your permissions/inheritance up.
- the context UI is in need of some attention, I agree, being able to edit the contexts in line is something I need to add at some point, for now you will just need to put up with deleting and re-adding the context (and double checking it is correct in the first place)

**Comment by BrainStone** [comment]
I think they meant that with the old editor when adding a permission the permission field would not be cleared.

**Comment by TechieBlort** [comment]
"The permissions don't transfer over from other groups."  To clarify I more meant that the permissions if you built them on another group then decide you don't want them there but in a different group it doesn't transfer it over to that group when clicked on so if you put 100+ permissions you have to re-input them into it and it's ok if it's a few permissions here and there but not if it's 30+ permissions.

**Comment by BrainStone** [comment]
Ah. So when changing the group you view the input fields get cleared, right?

**Comment by Turbotailz** [comment]
That makes sense. I do plan to add a feature that lets you move mass permissions to other groups. As for the input itself clearing, I might be able to refactor something to stop that happening.
