### ISSUE TITLE
Web Editor doesn't capitalize usernames properly, permissions per-user are not applied

### ISSUE THREAD

**Issue by Andrew1431** [lucko/LuckPermsWeb#142]
Hey! First time user here, absolutely love the GUI! I am experiencing one problem though, when I use the web editor to modify my per-user permissions, they are not applied when pasting the edits. It shows in the editor "andrew1431" when it should be "Andrew1431" and the permissions fail. Using the command in game worked though, so I am using that for now! Hope this helps =)

Edit: Using the commands to give myself the permissions in game worked !

**Comment by Andre601** [comment]
From what I know does it apply edits using the uuid and not the username.
Is your server in offline mode?

**Comment by Andrew1431** [comment]
Server is online, just installed the plugin. I would have assumed it uses the UUID but that doesn't appear to be the case, because when I paste the command (And see the confirmation in game, it shows "Permissions added for 'andrew1431'" and as such does not apply). Using the command manually in game to give myself the OP command worked though (as Andrew1431)

**Comment by Andrew1431** [comment]
Using Spigot (Well, PaperMC actually)

**Comment by Andrew1431** [comment]
Okay I take it back, it looks like it keeps lowercasing my name, and I am completely unable to add permissions to myself without doing it one at a time via minecraft commands

**Comment by Andrew1431** [comment]
Gah I don't really know what's happening. Do I have to reload something for changes to come in to effect? At this point I'm unsure where the bug lies, sometimes it works, sometimes it doesn't, so I'm going to close this for now until I can better understand what is happening.
