### ISSUE TITLE
Uncaught TypeError: data.sessions is not iterable

### ISSUE THREAD

**Issue by EvanSchleret** [lucko/LuckPermsWeb#145]
Hi,

I have this error on web editor (self-hosted) on editor feature : 
![image](https://user-images.githubusercontent.com/55502199/74785926-cd91ef80-52ab-11ea-9d39-8d50885444d6.png)

Thanks for your help !

**Comment by EvanSchleret** [comment]
update : I tried to print the content of data["sessions"] in the console and this value is empty

**Comment by Turbotailz** [comment]
Looks like you may be using the old version of the web editor. Which version of LuckPerms are you using?

**Comment by EvanSchleret** [comment]
Hi,
Thanks for your answer. I'm using the last version of luckperms web and version 5.0.78 of luckperms.

**Comment by Turbotailz** [comment]
Please note that the new web editor is on the [v2 branch](https://github.com/lucko/LuckPermsWeb/tree/v2)

The error you've shown is showing things from the old web editor (jquery is not used in the new version). The old editor is not compatible with LP v5.

**Comment by EvanSchleret** [comment]
Oh, thanks for your help.
Have a nice day (or night lol) !
