### ISSUE TITLE
Suggestion: Add extension sub-page

### ISSUE THREAD

**Issue by Andre601** [lucko/LuckPermsWeb#146]
It for sure would be good to have a sub-page that lists all (official) extension that LuckPerms currently has.
Something like https://luckperms.net/extensions would list all extensions, which could then be downloaded directly, similar to how you can download LP for the various different platforms it supports.

**Comment by Tobi406** [comment]
We now have an extension section on https://luckperms.net/download

**Comment by Andre601** [comment]
Looks weird on mobile

![image](https://cdn.discordapp.com/attachments/584040473186926623/712705256139784294/SmartSelect_20200520-183555_Chrome.jpg)

**Comment by Tobi406** [comment]
If ignoring the "LuckPerms 5.0 and above" text next to the "Default Assignments Extension", what is exactly looking bad? Maybe some more space between the first and second section?

**Comment by Andre601** [comment]
Exactly that text you mentioned.

I suggest putting it below the title when it is on mobile.

**Comment by Tobi406** [comment]
Could also do it like this: 
![image](https://user-images.githubusercontent.com/43016900/82473668-37e44700-9aca-11ea-9d97-cab775917079.png)
(Not sure how to put it below the title)

**Comment by Andre601** [comment]
Would be a solution
