### ISSUE TITLE
No option to remove context from new Web Editor

### ISSUE THREAD

**Issue by robotnikthingy** [lucko/LuckPermsWeb#147]
Looking at the new web editor I don't see an option to remove context.

I added 0 for key and 0 for value, and there was no way to remove it

**Comment by Turbotailz** [comment]
If you hover over the context you may notice there is a black `x` that appears, you can click this to remove it.

It might be a bit hard to see, the contrast isn't very good at all. I need to address some accessibility issues with the app.
