### ISSUE TITLE
After update to Version 5.0.x selfhosted Interface doesn't work

### ISSUE THREAD

**Issue by lastsamurai26** [lucko/LuckPermsWeb#148]
I have updated my Luckperm to version 5, now unfortunately the interface does not work anymore. 
When I type /lp tree, /lp editor or /lp verbose I get a link but when I call it I get a 404 error. 
What am I doing wrong. Which infos are needed ? 

I get i link like this 
 https://domain.de/edit/treeview/4cchiQbl21

**Comment by Andre601** [comment]
The editor received significant changes for version 5, to support creation and deletion of groups and tracks within the editor itself.
You have to update your code of the editor and also update your settings, to now point to `editor.domain.de`
I can't say how it is for the verbose and tree option.

**Comment by lastsamurai26** [comment]
This is what my settings look like 
web-editor-url: 'https://domain.de/edit/editor/'
verbose-viewer-url: 'https://domain.de/edit/verbose/'
tree-viewer-url: 'https://domain.de/edit/treeview/'

what do I have to change?

**Comment by Turbotailz** [comment]
Sorry, the documentation for hosting the web editor is quite outdated. You need to use the V2 branch for the new editor. It should work for the other two though.

**Comment by lastsamurai26** [comment]
ok how can i use the new interface. How can i install it

**Comment by Turbotailz** [comment]
The v2 readme has information on how to install, it's not a complete tutorial on how to set it up but once you build it is should be fairly easy to point to it however you want. Assuming you know the basics about web servers.
