### ISSUE TITLE
Not able to see permissions I have already selected

### ISSUE THREAD

**Issue by TheAusticCoder** [lucko/LuckPermsWeb#152]
Hey team so I have found a bug in your Web UI. When I am adding a lot of permissions they scroll beyond the edge of the screen. Meaning I can't see them anymore. Also one more thing please make the creation of groups a bit more streamlined because right now it's quite confusing maybe take out say the weight? and make everything a bit more clear to the somewhat newbie.

**Comment by Andre601** [comment]
Do you have a screenshot, gif or video about the scrolling issue?

Also, weight should be fairly understandable when you started using LP (and even if you just installed LP and straight up went for the editor should weight give you a clue for what it is)

**Comment by Turbotailz** [comment]
@TheAusticCoder please send a screenshot of what you are talking about, also the version of browser you are using.

**Comment by Turbotailz** [comment]
As for your suggestion about adding groups, those options are very useful for people who know what they do. Taking these options away will only annoy more people.

The very best I can do is add tool tips to explain what each field means.
