### ISSUE TITLE
Not all Essentials permissions appear

### ISSUE THREAD

**Issue by Macintosh-Fan** [lucko/LuckPermsWeb#153]
I am searching for permissions in essential and they do not appear. Like essentials.spawn

**Comment by Andre601** [comment]
The editor won't show permissions that where not checked/loaded by LP before.
This essentially means, that essentials.spawn wasn't checked between the time of the server starting and you running the editor command.
The permissions of Essentials(X) can be found here: https://essinfo.xeya.me/permissions.html
