### ISSUE TITLE
Prefix and suffix not working.

### ISSUE THREAD

**Issue by VerifyGod** [lucko/LuckPermsWeb#154]
I have the plugin LuckPerms and changed the default group prefix to &8&l[&7&lMember&8&l] and a suffix &8&l[&7&lTest&8&l] and gave myself the rank, but when I talk in the chat, it doesn't seem to show the prefix and suffix.
![2020-03-02_22 35 58](https://user-images.githubusercontent.com/47757820/75715546-42b2eb00-5cd6-11ea-9c80-a95dcea731ad.png)

Maybe I am just dumb and forgot something and if you found a problem then please comment the problem.

Nvm found the problem.

**Comment by Turbotailz** [comment]
I'm guessing you didn't have a chat plugin configured.

Anyway this was posted to the wrong repository. Please use lucko/LuckPerms next time.
