### ISSUE TITLE
Addition in the permissions editing panel

### ISSUE THREAD

**Issue by Kramels23** [lucko/LuckPermsWeb#156]
Hello,
Would be great if there was a "choice of permission action servers" box when editing a permission. Like this, the admin can activate or not different permissions to a grade in different bungee servers.

Have a good day ;)

**Comment by Andre601** [comment]
I don't quite understand what you want.
If you want an option to set a perm per world/server, then this is already a thing:
Just click on the field under the "Context" column and in the opening window, set "world" or "server" (without quotes) as key and the world/server name as value.

**Comment by Kramels23** [comment]
This is exactly what I wanted to know. thank you very much and good day
