### ISSUE TITLE
auto split ':' in context

### ISSUE THREAD

**Issue by RimuruChan** [lucko/LuckPermsWeb#157]
like default context key is server(really useful for me)
it is a pain to copy it again and again
or u can add auto split like if i paste "server:xxx"
it auto set to
key value
server xxx

**Comment by BrainStone** [comment]
Do you mean auto split?

**Comment by Sprite233** [comment]
yes 
sry for my poor english...

**Comment by Tobi406** [comment]
We also have to consider that there are people who want to use `:` in context, [EssentialsX does this](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/perm/PermissionsHandler.java#L184L188) for example

**Comment by Turbotailz** [comment]
> We also have to consider that there are people who want to use `:` in context, [EssentialsX does this](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/com/earth2me/essentials/perm/PermissionsHandler.java#L184L188) for example

Very good point! It seems that this will be a standard for other plugins supplying context that the contexts are name-spaced like `plugin:context`. Will close this for now. Remember you can add multiple permissions at once with the same context, also you will be able to bulk update contexts when #285 is merged.
