### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by alexandre14062** [lucko/LuckPermsWeb#160]
When changing the weight of groups it sometimes happens that the button to remove certain groups disappear. In addition, the weight value is not centered properly. Look at this:

![image](https://user-images.githubusercontent.com/20821366/76468533-87b7db00-63c2-11ea-962f-c1dc783d1b30.png)

**Comment by Turbotailz** [comment]
This will be because the default group cannot be deleted, therefore the button does not exist and will not push the weight to be in line with the other weights.

An easy fix though, thanks for reporting.

**Comment by Andre601** [comment]
Yup. Have this too and a fix to allign it properly would be nice to have as it looks really out of place.
