### ISSUE TITLE
Web editor does not show changes to tracks

### ISSUE THREAD

**Issue by garrettsummerfi3ld** [lucko/LuckPermsWeb#162]
Opening up a new web editor instance to modify track order does not apply.

For instance: Say I have a `staff` track and I accidentally did not order out my groups in the Web Editor before making the track. Something like this:
![image](https://user-images.githubusercontent.com/7040719/76577531-b5208980-6493-11ea-88e3-43ab0088622d.png)

I launch an instance of the web editor and make my changes to the order. Once I make my changes and run the `lp apply` and the edits are not transferred back from the web editor.

Nothing from what I am seeing in `lp verbose` is showing anything getting denied or going nuts with the permissions.

A workaround to this is to add/set/modify a permission in any group in the affected track, and the reorder of the track will occur.

Any other prevalent information:
```
Server Version: Paper 1.15.2
LuckPerms Version: 5.0.83
```

**Comment by Turbotailz** [comment]
Yeah I know why this happens, thanks for the report.

**Comment by garrettsummerfi3ld** [comment]
Thank you for this. Not to pester you more but what is the cause?

**Comment by Turbotailz** [comment]
Sorry I thought I knew why but it turns out the editor is doing the right thing. I've opened lucko/LuckPerms#2144 so Luck can take a look at it.

**Comment by Turbotailz** [comment]
This should be fixed now in LuckPerms v5.0.126

![image](https://user-images.githubusercontent.com/10846855/78551837-b9995180-7849-11ea-9c33-eb1ddfbb92c8.png)
