### ISSUE TITLE
Permissions missing

### ISSUE THREAD

**Issue by Redstonico** [lucko/LuckPermsWeb#163]
There are multiple permissions missing when you have more plugins, which means that if i e.g add a plugin, the permissions sometimes not even show up in the webeditor

**Comment by BrainStone** [comment]
You can add any permissions in the web editor, even when it doesn't show up. The permissions that show are merely suggestions based on what LP has seen since the server started. And it's quite common that not all are there.

**Comment by Turbotailz** [comment]
Running a command like `/help` can help cache the permissions in LP and then they will appear in the permission list. Like Brainstone said, LP only suggests permissions that it knows about, it doesn't mean the permission isn't available (best to consult the documentation for your plugins or use Verbose mode).

Not a web editor issue, closing.
