### ISSUE TITLE
Info command not showing online player

### ISSUE THREAD

**Issue by Lurreisper** [lucko/LuckPermsWeb#164]
Hi guys, I'm with a doubt: Well, all my servers are syncing by a database, but when I try to execute "/lp user <nickname> info" it's not showing wich server he's connected.
For example: If I'm on RankUP and execute the command on Lobby, it shows I'm offline, but when I execute it in SkyWars it work perfctly (obviously).
Does anyone know what can it be?

RankUP Command: 
![image](https://user-images.githubusercontent.com/37253796/76704063-34d96e80-66b5-11ea-8fc8-369e11786e76.png)

Lobby Command: 
![image](https://user-images.githubusercontent.com/37253796/76704080-4d498900-66b5-11ea-86c1-f72f15080ee4.png)

**Comment by Turbotailz** [comment]
Can you please open this on the correct repository?

https://github.com/lucko/LuckPerms

Also, wild guess, I assume this is because that user isn't on the Lobby server, so LP thinks they are offline. Get that user to enter the Lobby server and the contexts will be applied.
