### ISSUE TITLE
 Prefixes don't show up at all

### ISSUE THREAD

**Issue by Selfoccate** [lucko/LuckPermsWeb#165]
When I try to setup the prefixes, they don't come up at all on the rank they should show up on. I received some help from someone on Discord, and we weren't able to get to the issue. Nothing seems to work.

**Comment by Andre601** [comment]
Does it show when you run `/lp user <user> info`?
If it does, then LP did its job and it is now up to whatever plugin you want to use for showing the prefix in chat, tab list, scoreboard, ...

Also, this is imo not really an issue with the web editor. But to make things clear: `prefix.<weight>.<prefix>` is the syntax/permission used for displaying the prefix (Replace `<weight>` with a number and `<prefix>` with your actual prefix)

**Comment by Selfoccate** [comment]
Ok, thank you.

Yes it does show up when running that command, what is the best chat plugin you would suggest I use? I currently have tried EssentialsXChat and UltimateChat and neither seem to work.

**Comment by Andre601** [comment]
EssentialsXChat should work just fine, as long as you also have EssentialsX itself and Vault installed.

**Comment by Selfoccate** [comment]
Yeah, I have all of them installed, and they don't work with it. How should I edit the configs to make them work together?

**Comment by Turbotailz** [comment]
Not a web editor issue.

Please use https://github.com/lucko/LuckPerms for general LP issues.

Or feel free to join our discord for more efficient support https://discord.gg/luckperms
