### ISSUE TITLE
Put an "give all commands" in the web editor 

### ISSUE THREAD

**Issue by rockey86** [lucko/LuckPermsWeb#167]
i wanted to create an owner rank but i have alot of plugins and who wants to sit there for an hour just clicking away at each individual command, if there is already a solution to this, please let me know

**Comment by Turbotailz** [comment]
You need to learn what wildcards are.

Just add `*` and you'll get every permission. It's not really recommended
as you'll inherit some unwanted permissions so use it at your own risk.
