### ISSUE TITLE
deopped and some rank postions names are glitched out

### ISSUE THREAD

**Issue by Bot1232134** [lucko/LuckPermsWeb#172]
Some of my ranks like a builder and the default rank names glitch out as shown below. the owner and admin go away when de opped. in the picture, I am an opped owner and my other owner is a non opped owner. his name his completely random for some reason
![problem](https://user-images.githubusercontent.com/52546161/77731732-1a629780-6fc9-11ea-91e2-2af283b53647.png)

**Comment by Turbotailz** [comment]
Not a web editor issue.

Read here:
https://github.com/lucko/LuckPerms/wiki/FAQ#why-are-prefixessuffixes-not-working

If it still isn't working then join our [Discord](https://discord.gg/luckperms)
