### ISSUE TITLE
dont have permission

### ISSUE THREAD

**Issue by Alvarol10** [lucko/LuckPermsWeb#173]
I create a grupo with some permissions and i introduce people there but when they try ro use the commands they donth have permission

**Comment by Andre601** [comment]
Please provide more information about your issues like your LP version, server type and version, what commands you used, etc.

In most cases is your issue simply wrong permissions. Please check the docs/plugin page of whatever plugins you use and that you want players to use or use the [verbose command](https://github.com/lucko/LuckPerms/wiki/Verbose) of LuckPerms.
