### ISSUE TITLE
Siggestion: Allow adding Suffix/Prefix on Web editor

### ISSUE THREAD

**Issue by L0rdLogan** [lucko/LuckPermsWeb#174]
I love the web editor, but the ability to add (and preview) the suffix/prefix from the web interface would make like easier

**Comment by BrainStone** [comment]
You can already add them with ``prefix|suffix.<weight>.<prefix|suffix>`` like ``prefix.123.&6Test``.

**Comment by L0rdLogan** [comment]
Thnak you, was not aware. I know I can also do this in-game too, but the web interface is so easy!

**Comment by BrainStone** [comment]
Only thing is that you can't preview them.
