### ISSUE TITLE
Nick Color

### ISSUE THREAD

**Issue by kubaxyz** [lucko/LuckPermsWeb#176]
Hi,
I'm using LuckPerms, Vault and VaultChatFormatter.
Is some way how to have other nick colors for other groups?
Thank you for help. Kuba

**Comment by Laarryy** [comment]
Nicknames aren't handled by any of those plugins. Preface a nickname with a colour code from https://wiki.ess3.net/mc/ to change its colour. If it's always red, you need to configure your EssentialsX config. Feel free to ask any more questions on the discord! 

https://discord.gg/luckperms
