### ISSUE TITLE
Gamemode permission issues

### ISSUE THREAD

**Issue by CubzCaleb** [lucko/LuckPermsWeb#177]
I want to only give gamemode spectator to a certain group how do I do that? Without giving gamemode creative to that group.

**Comment by Turbotailz** [comment]
You need a plugin that can provide permissions like that, EssentialsX is a good option for Bukkit servers.

This has nothing to do with the web editor so I will close this. Join the [discord](https://discord.gg/luckperms) if you need any more help.
