### ISSUE TITLE
World permissions

### ISSUE THREAD

**Issue by Alv5ro** [lucko/LuckPermsWeb#178]
I can't set the permsissions per world on my bungeecord, it seems to only be global.

**Comment by Laarryy** [comment]
Use the `world` context key in bungee-lp to define server context. It's weird, I know. See #1668 it's already been suggested, even.

**Comment by Alv5ro** [comment]
cheers, could you link the page, I can't find it.

**Comment by Laarryy** [comment]
https://github.com/lucko/LuckPerms/issues/1668
