### ISSUE TITLE
Add a classic mode for the LuckPerms editor

### ISSUE THREAD

**Issue by PhoenixHaven** [lucko/LuckPermsWeb#180]
I recently upgraded to the latest version of LuckPerms and the new editor looks ugly. The old editor looked so much cleaner and didnt have so many buttons in weird places. The classic one was far easier to use and didnt have stuff that you can do in game, like parent groups. Just an option in the config or a command to go back to classic mode would be amazing.

**Comment by Turbotailz** [comment]
As you can see from the big red BETA at the top, it's not in a fully finished state and constructive feedback may help make it look a lot better.

I will not work on the old editor code, and some would need to be done on it to have it work with current versions of LuckPerms. Feel free to fork it and make it happen.

If you hate it that much, you can always downgrade to LuckPerms v4 so you can use it again.
