### ISSUE TITLE
Permission problem between Towny and Luckperms

### ISSUE THREAD

**Issue by math3x3** [lucko/LuckPermsWeb#184]
So basically luckperms seems to override towny permissions, so player dont have towny permissions at all. I can't manually add them to their group because each towny rank have their own permissions.

Anyone knows how to set that up ?

**Comment by Andre601** [comment]
LuckPerms doesnt *"override towny permissions"* as it does nothing more than handle permissions.
The fact that your players don't have rights mean that you either didn't give the right permission, or no permission at all.

**Comment by math3x3** [comment]
normally you dont need to give them permission since towny has its own permission file

**Comment by Turbotailz** [comment]
Not a web editor issue, open an issue on the LuckPerms repo or join the discord to get further support.
