### ISSUE TITLE
Question WebGUI -Display

### ISSUE THREAD

**Issue by CloudeLecaw** [lucko/LuckPermsWeb#185]
![image](https://user-images.githubusercontent.com/12080017/78769975-4baa7280-798e-11ea-90ae-02f2ce5a101b.png)

I have a question about the WebGUI

You can see it shown an amount of 500 Users

![image](https://user-images.githubusercontent.com/12080017/78770408-d12e2280-798e-11ea-9895-cfcba178bef0.png)

The real value of Playerfiles is 2130. is it possible to list them all in the GUI?
and if not is it still possible to give/take perms to the playersfiles that are needed, even if they not listet in the 500?

**Comment by Turbotailz** [comment]
This is something that needs to be done from the plugin side, I would open an issue there instead.

https://github.com/lucko/LuckPerms/issues

**Comment by BrainStone** [comment]
The question is, why exactly do you want to edit all 2126 users?

What do you want to achieve?

Sounds like a case of the [XY problem](http://xyproblem.info/) to me

**Comment by CloudeLecaw** [comment]
nono BrainStone i never said i wanne edit them als. But the chance is high that the may 20 that i want to edit are not listet in this 500.

**Comment by BrainStone** [comment]
If you just open a normal editor session you will only get the online players.  
And if you want to edit a specific user you can of course also use ``/lp user <user> editor``.

**Comment by CloudeLecaw** [comment]
hm i tried the name of a not listet player /lp user Blueeyestar editor
![image](https://user-images.githubusercontent.com/12080017/78779495-57516580-799d-11ea-859f-2aeb1ab33eab.png)
i need to use the UUID...
![image](https://user-images.githubusercontent.com/12080017/78779781-d050bd00-799d-11ea-9a9f-e932a66be822.png)
 then it works... is there any chance to search for the playnername when the player is not online too?
looking inside the players folder showed me the yaml i use are stored as <UUID>.yml

i wanne use yml because its the format i more conformal with
