### ISSUE TITLE
Expires in - start with 1970...

### ISSUE THREAD

**Issue by CloudeLecaw** [lucko/LuckPermsWeb#186]
If you try to change the expiering time from the WEB GUi (after starting the GUI)
The calendar starts from Jan 1970 - so u have to scroll much if u wanne start from 2020 or longer..

![image](https://user-images.githubusercontent.com/12080017/78788644-625fc200-79ac-11ea-99ce-08324b561ef7.png)

If u cange an expire date (from the GUi or not) it normaly is not laying in the past..
So it would make sense if the calendar there could start from current day..

is this possible to change?

**Comment by Turbotailz** [comment]
This will be a bug from a recent update I think. Thanks for reporting.
