### ISSUE TITLE
How i can to do that?

### ISSUE THREAD

**Issue by r3dmistyle** [lucko/LuckPermsWeb#188]
I have LuckPerms and Multiverse. I want to start on world "spawn", where I have only one permission: multiverse.core.tp.spawn. When i will teleport, i will have all of perms. Also sorry for my English.

**Comment by Andre601** [comment]
This isn't really related to Web editor.
Just set a context with `world` as key and the name of the world as value,

**Comment by r3dmistyle** [comment]
> Это не имеет никакого отношения к веб-редактору.
> Просто установите контекст в `world`качестве ключа и имя мира в качестве значения,

Thank for you answer. But can you send me where i need to write it? How can i select player who touched a button? Again, sorry for my English.

**Comment by benwoo1110** [comment]
For multiverse permissions: https://github.com/Multiverse/Multiverse-Core/wiki/Big-List-O-Permissions#teleport-permissions
