### ISSUE TITLE
Web editor context value for server is not showing correctly 

### ISSUE THREAD

**Issue by Flux-Boi** [lucko/LuckPermsWeb#190]
As seen in this image, when I go to try and set a context that involves per server permissions, the value popup does not display correctly.
https://i.imgur.com/ZGUcVcO.png

For context I have 3 servers: survival, creative and hardcore (all defined in the config.yml for luckperms in their respective servers, all using mysql) and only the letters of survival are popping up. However the value, when manually typed out, seems to still apply the specified permission node correctly.

Editor link:
https://editor.luckperms.net/cuwkVe6CqQ

**Comment by Turbotailz** [comment]
Lol that's weird, thanks for reporting

**Comment by Turbotailz** [comment]
Fixed
