### ISSUE TITLE
Prefix not showing in Chat

### ISSUE THREAD

**Issue by 4xk** [lucko/LuckPermsWeb#191]
![hi](https://user-images.githubusercontent.com/63573183/79091242-8ad41d00-7d1a-11ea-823a-aa089a108121.PNG)
![2020-04-13_00 04 41](https://user-images.githubusercontent.com/63573183/79091259-9b849300-7d1a-11ea-85d6-b129826152c6.png)
I dont know what im doing wrong i added the prefix if you see above please help

**Comment by benwoo1110** [comment]
You will need to set prefix priority as such: prefix.<priority>.<prefix_name>

highest the priority prefix of the groups that you are in will show.

how support, please join the discord at https://discord.gg/luckperms

**Comment by 4xk** [comment]
You will need to set prefix priority as such: prefix.[priority].[prefix_name]??
Is there a way I can get in a discord call with you for a short tutorial?

**Comment by benwoo1110** [comment]
https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta#how-does-prefixsuffix-weight-work

you can join the discord, there will be many ppl that can help you with your issue there.

**Comment by 4xk** [comment]
> https://github.com/lucko/LuckPerms/wiki/Prefixes,-Suffixes-&-Meta#how-does-prefixsuffix-weight-work
> 
> you can join the discord, there will be many ppl that can help you with your issue there.

ok thanks for the quick response!
