### ISSUE TITLE
Notepad editor

### ISSUE THREAD

**Issue by Mickinskis** [lucko/LuckPermsWeb#193]
Love what you did with the editor but tbh there was no real reason to remove the notepad editor. Imo it was WAY easier to use than the internet one. I think you should give the ability for server moderators to choose which editor they want to use

**Comment by Turbotailz** [comment]
Notepad editor?

Do you mean editing your database with text based editors, like yaml? That's always been a feature of LuckPerms. Maybe check the config under "storage-type".
