### ISSUE TITLE
Perms

### ISSUE THREAD

**Issue by nuggetwiz** [lucko/LuckPermsWeb#195]
When i add a permission to a group like essentials.fly or essentials.* and i go to a different group or tab and then back to the permission i just added, it disappears. For example, i go to group owner, i add the permission essentials.fly, i go to group vip, i go back to group owner, the permission is gone and when i save and type the command in minecraft it says no changes we added.

**Comment by BrainStone** [comment]
You have to click the <kbd>+</kbd>-Button on the bottom right to actually add it.

**Comment by nuggetwiz** [comment]
oooooooooohhhhhhhhhh thank you
