### ISSUE TITLE
Duplicate permissions.

### ISSUE THREAD

**Issue by qSeek** [lucko/LuckPermsWeb#199]
I think that it would be cool a command/web panel option to duplicate a bunch of permissions with a different context.
For example if I have these permissions:
https://i.imgur.com/5LEMlGa.jpg
to be able to select all permissions with content server=lobby and duplicate them with context server=skyblock .

**Comment by Turbotailz** [comment]
Something like this is planned for a future release.

In the meantime, if you find there are a lot of the same permissions you need to use in different contexts I can suggest creating a group with the permissions (set to global) and then add the group with the desired contexts, night make it quicker for you.

**Comment by lucko** [comment]
This is probably going to be mostly resolved by https://github.com/lucko/LuckPerms/pull/2300

Of course there will still be cases where duplicating will be necessary / useful - just less often than at the moment 😃
