### ISSUE TITLE
copy paste

### ISSUE THREAD

**Issue by Evergreen1213** [lucko/LuckPermsWeb#200]
a way to copy the group perms list so that you can paste it in a different server.

**Comment by Turbotailz** [comment]
This is too vague. What exactly are you wanting to do? Because there are several methods of doing this but I can't suggest any without knowing what you're trying to do.

**Comment by MeloMike-xD** [comment]
You are going to need to set up luckperms with a `my sql database`, or other remote databases. How to do this? More information about how to do this will be in https://github.com/lucko/LuckPerms/wiki/Syncing-data-between-servers 
If you have an error go to the luckperms discord and post it in general, people there helped me when I had to do this! 

LuckPerms Discord: https://discord.gg/luckperms
