### ISSUE TITLE
World Permissions for the Website Editor!

### ISSUE THREAD

**Issue by IceMcFall** [lucko/LuckPermsWeb#202]
WORLD PERMISSIONS ( I know you can put a world context in the permission )

  So, before I state why I need this, let me tell you what I want. I think it will be a great idea for there to be an area in the "luckperms editor website" where you can select between worlds or something like that. It would be located on the right with groups and users. It would show all the worlds you have including "global" which is for all worlds. When you click on a world, you can put the permissions, prefixes, and other for players only in that world. If you select global instead of a specific world, then what you put in it will affect all worlds. If you type a permission without selecting any world at all, it will be automatically added to the "global" world section.

  The reason I would like this world feature would be very helpful, to make it easier as well as saving time. I need it right now, because in order for me to make a permission "false" in a few worlds, I have to copy the same permission over and over with each world I want the permission in with the permission world context.

This issue example: ( It's about the gamemode permission I don't want usable in the survival world )
![image](https://user-images.githubusercontent.com/63832091/79530174-39869f00-8034-11ea-92d9-8e8fae3bb4ef.png)

**Comment by Andre601** [comment]
So the editor should display permissions, groups, etc based on what world you have selected?
Like an advanced filter of sorts?

**Comment by lowlevelm** [comment]
That would add unneeded complexity

**Comment by Turbotailz** [comment]
Yeah I don't think adding this will be very beneficial to many people and may add more confusion to the mix. If you find you are having issues using contexts currently then you may need to look into setting up [custom contexts](https://github.com/lucko/LuckPerms/wiki/Context#default-contexts) to possibly make your life easier.
