### ISSUE TITLE
Have applyedits command '/' free

### ISSUE THREAD

**Issue by Laarryy** [lucko/LuckPermsWeb#203]
Brought up to me, wouldn't it be better to make the applyedits command from the editor copy without the `/` ? That way it can be pasted into console more smoothly, and players still type `/` to open the command ingame and then they just paste it there. Can't think of any reason not to, and if you want you can just point me the where this is in the code and I'll just remove the `/` from the format and make a PR.

**Comment by Laarryy** [comment]
Notice: brought up to me just now that the person who brought it up to me also made one... but on Turbo's repo. Closing this!

**Comment by Turbotailz** [comment]
Turbotailz/LuckPermsWeb#34

**Comment by BrainStone** [comment]
See my comment on the issue: https://github.com/Turbotailz/LuckPermsWeb/issues/34#issuecomment-615197543
