### ISSUE TITLE
Update The Permissions Suggestions Menu

### ISSUE THREAD

**Issue by Pika1998** [lucko/LuckPermsWeb#204]
As i can see right now there is no multi select or selection options in the permissions selection, it would be great to add that as it will save alot of time and enhance the UI

![image](https://user-images.githubusercontent.com/36433104/79691358-a2f8ee80-827c-11ea-804a-5d6fff55c732.png)

**Comment by Turbotailz** [comment]
Are you sure?
![image](https://user-images.githubusercontent.com/10846855/79703529-b98c5d80-82ef-11ea-9895-0c0ec95d136c.png)

**Comment by Pika1998** [comment]
Can you please tell me how did you do it, when i pressed enter to select nothing happened

**Comment by Turbotailz** [comment]
Pressing enter should select it. You can also select items by clicking on them.

If it's not working then there is probably an error. What browser are you using?

**Comment by Pika1998** [comment]
I'm using Google Chrome

**Comment by Pika1998** [comment]
Issue solved
