### ISSUE TITLE
Web editor shows group perms set to false as parent groups in the UI

### ISSUE THREAD

**Issue by ronthecookie** [lucko/LuckPermsWeb#213]
I have a node `group.foo` set to false and it still shows up in the parent groups list:
![image](https://user-images.githubusercontent.com/25263210/80647501-3d281600-8a77-11ea-826d-d050cb9cb459.png)
![image](https://user-images.githubusercontent.com/25263210/80647503-3f8a7000-8a77-11ea-8a90-ea2f1704f880.png)

**Comment by ronthecookie** [comment]
Bump

**Comment by Turbotailz** [comment]
Fixed in f33a5f01e2a2e2120537cb09d66f6ac1027d1a2c
