### ISSUE TITLE
Can't set a permission not listed in enter menu

### ISSUE THREAD

**Issue by sibraxlis** [lucko/LuckPermsWeb#214]
Typing a permisision should also default to the typed permission when hitting enter.

**Comment by Laarryy** [comment]
you can type it out all the way and hit enter, no? Please describe exactly what you mean by can't set.

**Comment by Laarryy** [comment]
Making lazy suggestions or bug reports helps nobody and decreases the likelihood of your issue being resolved. Please, put effort into it so your meaning is clear and any issues can actually be seen to.

**Comment by BrainStone** [comment]
Pretty sure it does already. We nee more info

**Comment by sibraxlis** [comment]
I figured out what my issue is. it seems to be auto selecting things from the list when my cursor isn't over the item in the menu, so if I hit enter it's auto filling things that i'm not trying to type in.

**Comment by Turbotailz** [comment]
It says "Push enter to select" next to each item that is highlighted. There are a couple other issues related to the behaviour of the select menu, so I will close this.
