### ISSUE TITLE
Permissions should be auto added when changing groups instead of wiped.

### ISSUE THREAD

**Issue by sibraxlis** [lucko/LuckPermsWeb#215]

**Comment by Laarryy** [comment]
What? This has nothing to do with LuckpermsWeb and no description is provided. If you want users to keep the last group's perms, either set the last group as a parent of the next one, or add the group as a new parent and don't remove the old one

**Comment by Laarryy** [comment]
Making lazy suggestions or bug reports helps nobody and decreases the likelihood of your issue being resolved. Please, put effort into it so your meaning is clear and any issues can actually be seen to.

Including no description is a surefire way to get the issue closed prematurely, even if there is something valuable you have to say.

**Comment by BrainStone** [comment]
I mean I know what you want but I disagree. Adding the permissions should always be a deliberate act.  
At most it should warn you when changing or better even keep the data for until you come back.

And for those that don’t quite get what he wants (@Laarryy *cough cough*) he’s asking for permissions that are not yet added but typed out in the fields to be added automatically when switching to another group. Because currently the permissions just get removed.

**Comment by Laarryy** [comment]
It is, as far as the English language goes, impossible to be 100% sure that anything in particular is meant at all. The lack of description is bad practice and clears nothing up, and while your assessment (translation?) is definitely better than mine, there is no reason to leave a lazy issue like this that is incredibly unclear. Thanks for letting me know that this is what they'd like, @BrainStone but it really would be nice to be able to tell from just the main issue.

**Comment by BrainStone** [comment]
I mean it’s pretty clear based of the title. Would a description have helped? Sure. Is it necessary? I don’t think so in this case.  
Though admittedly I received a similar complaint before so I was already aware of the behavior.

**Comment by Turbotailz** [comment]
It's a very vague description and I probably wouldn't have understood it without @BrainStone's interpretation.

This has been reported several times so this issue isn't necessary. It will be fixed at some point in the future.
