### ISSUE TITLE
 i can't create a track in Luck Perms what is happeing

### ISSUE THREAD

**Issue by Aguiar10** [lucko/LuckPermsWeb#217]

**Comment by Turbotailz** [comment]
No idea. You haven't provided any information :(

**Comment by Aguiar10** [comment]
you cant help me
?


Sam Goodger <notifications@github.com> escreveu no dia sexta, 1/05/2020
à(s) 08:47:

**Comment by BrainStone** [comment]
Not untill you start providing information.

Like what you are doing, what's happening, etc.
Keep in mind we can't see your screen. Try to be as descriptive and detailed as possible. Screenshots help greatly!

**Comment by lucko** [comment]
Possibly related to https://github.com/lucko/LuckPerms/issues/2144 ??

Either way, no reply so I'm gonna close for now.
