### ISSUE TITLE
how to make that the player can do the command only in the spsific world

### ISSUE THREAD

**Issue by eliranas** [lucko/LuckPermsWeb#218]
am using the beta virson of luckperms and i want to make players to do /fly only in the lobby and NOT in survival world please help

**Comment by Tobi406** [comment]
What do you mean with "beta"? 
Anyways, take a look at [context on the wiki](https://github.com/lucko/LuckPerms/wiki/Context), using one you can set the permission for `/fly` only in the `lobby` world

**Comment by Andre601** [comment]
There's also a [section on the web editor page](https://github.com/lucko/LuckPerms/wiki/Web-Editor#editor-context) explaining how to add context
