### ISSUE TITLE
Edits can't be applied anymore

### ISSUE THREAD

**Issue by Nolram12345** [lucko/LuckPermsWeb#220]
After using the web editor a few times, edits can't get applied anymore. It simply says that there were no changes returned.

**Comment by Andre601** [comment]
What steps did you do?
And to be clear: The editor won't auto-update to the changes. Once you applied the changes will you need to run the editor command again, to have the up-to-date info.

**Comment by Turbotailz** [comment]
Are you generating a new URL every time?

**Comment by Nolram12345** [comment]
Yes, I was.
I used the command but it returned nothing, I tried reloading aswell.

**Comment by BrainStone** [comment]
I mean as long as you don't reload the editor page, you don't have to open a new session every time.

But just to be clear, you restarted the server?

**Comment by Nolram12345** [comment]
Well, no I haven't, never did in the past but everything used to work regardless.

**Comment by BrainStone** [comment]
Just give it a try.
