### ISSUE TITLE
not all users in editor web

### ISSUE THREAD

**Issue by AnthoBear** [lucko/LuckPermsWeb#227]
hello ... I am new to this platform, I am using your plugin and in the web editor, in the USERS tab only 11 users out of 20 appear who have logged into my server, I cannot configure some things from the web editor since There are not all my users, I hope it can be fixed
![image](https://user-images.githubusercontent.com/65104660/81491663-17a4c480-924e-11ea-8f3e-91262055822a.png)
![image](https://user-images.githubusercontent.com/65104660/81491678-402cbe80-924e-11ea-8e56-0d9573524f74.png)

👍

**Comment by Turbotailz** [comment]
It will only show players that have logged in to the server since LP was installed.

**Comment by AnthoBear** [comment]
> It will only show players that have logged in to the server since LP was installed.


everyone entered when the plugin was already installed

**Comment by Turbotailz** [comment]
Then it is only showing who is online.

This isn't handled by the web editor itself so if you believe it to be an actual bug then you need to raise it over at https://github.com/lucko/LuckPerms
