### ISSUE TITLE
World / Server selector in context menu

### ISSUE THREAD

**Issue by JasonHorkles** [lucko/LuckPermsWeb#232]
If you have a lot of worlds / servers in the context menu when adding a new permission node, it will display past the bottom of the screen and you aren't able to scroll down to see the whole list
There should either be a scroll bar inside that list or something so that you can see everything properly

**Comment by Turbotailz** [comment]
Thanks, it's been on my mind ever since I created it and haven't really bothered to fix it lol.

I think setting a max height to the element and adding a scrollbar is the best option.
