### ISSUE TITLE
/help command will not work while using luckperms and nucleus

### ISSUE THREAD

**Issue by BlittyBB** [lucko/LuckPermsWeb#234]
Does anyone know why I do not have permission to the /help command?

**Comment by Laarryy** [comment]
Because you haven't added the right permission node to yourself?

Use [verbose](https://github.com/lucko/LuckPerms/wiki/Verbose) to find the node you need to add to yourself.

**Comment by BlittyBB** [comment]
> Because you haven't added the right permission node to yourself?
> Use verbose to find the node you need to add to yourself.

It says Minecraft.command.help is set to "TRUE" under the permission

**Comment by RJHaytree** [comment]
Sponge overrides the Minecraft help command with it's own. A detailed list of sponge commands can be found in their documentation https://docs.spongepowered.org/stable/en/server/spongineer/commands.html. This shows that the permission node for the help command is `sponge.command.help`
For future reference, as Laarryy stated you can use the LuckPerms verbose command to assist you in identifying the permission you are lacking.

**Comment by BlittyBB** [comment]
> Sponge overrides the Minecraft help command with it's own. A detailed list of sponge commands can be found in their documentation https://docs.spongepowered.org/stable/en/server/spongineer/commands.html. This shows that the permission node for the help command is sponge.command.help
> For future reference, as Laarryy stated you can use the LuckPerms verbose command to assist you in identifying the permission you are lacking.

I don't even have access to /sponge:help in game and I cannot activate it in the console
