### ISSUE TITLE
online players duped

### ISSUE THREAD

**Issue by Havoc925** [lucko/LuckPermsWeb#235]
When a player is online they show up twice with duplicated perms 

![Annotation 2020-05-12 234804](https://user-images.githubusercontent.com/41883777/81780262-1b815280-94ab-11ea-83b2-b6dd569158b8.png)

**Comment by Turbotailz** [comment]
This would indicate something is up with your database, probably. The information that is sent to the webeditor from LuckPerms has somehow gathered a user twice. It's not really an issue with the editor itself but I can fix it if desired (though this would remove any visibility of such issues in the future).

**Comment by Turbotailz** [comment]
Could you please provide a URL to this editor session?

**Comment by Havoc925** [comment]
https://editor.luckperms.net/l2wo5oZPg8
