### ISSUE TITLE
Duplicate Users

### ISSUE THREAD

**Issue by squidee100** [lucko/LuckPermsWeb#236]
After a succesful save, opening the editor up from a new command will create duplicates of the targets of the latest update. Say, "squidee_" is an admin and a new permission node was added and saved, the next time it's loaded up, there would be 2 squidee_'s.

I don't know if this is the real cause of the issue, this is just how I replicated it.
![2020-05-17 01_57_59-LuckPerms](https://user-images.githubusercontent.com/29834597/82124351-e2feb300-97e1-11ea-870e-005d8b0e1667.png)

Edit: Sorry if I didn't add the bug flair. I'm new to issue posting on GitHub :P

**Comment by BrainStone** [comment]
Update LuckPerms. It has been fixed recently

https://luckperms.net/
