### ISSUE TITLE
Parent "x" button to delete

### ISSUE THREAD

**Issue by squidee100** [lucko/LuckPermsWeb#237]
The x button will not work but deleting the permission node for the parent rule itself will work as an alternative.

![2020-05-17 06_39_24-LuckPerms](https://user-images.githubusercontent.com/29834597/82129831-2882a680-9809-11ea-96cf-c6e2374e0cac.png)

**Comment by BrainStone** [comment]
Is that happening for players or for groups?

**Comment by squidee100** [comment]
Both players and groups.

**Comment by Turbotailz** [comment]
Ah yeah I changed some stuff recently with the parent groups and forgot
about the delete button, thanks!

**Comment by Turbotailz** [comment]
Fixed in https://github.com/lucko/LuckPermsWeb/commit/a1d4e5b89e60bfe506feb3603b950c54bb0d742a
