### ISSUE TITLE
Support more than one value per context

### ISSUE THREAD

**Issue by lucko** [lucko/LuckPermsWeb#238]
lucko/LuckPerms#2300 

The payload will expect contexts to be serialised as follows:

#### Single values are serialised as follows:
```json
{
  "server": "survival",
  "world": "overworld"
}
```
or when sending back to the server, it's ok to unnecessarily wrap single values in an array:
```json
{
  "server": "survival",
  "world": ["overworld"]
}
```

#### and multiple values like so:
```json
{
  "server": "survival",
  "world": ["overworld", "nether"]
}
```

**Comment by lucko** [comment]
Oh I guess maybe a duplicate of #181

**Comment by Turbotailz** [comment]
Kind of, but this one has more info so I'll close that!
