### ISSUE TITLE
Prefix problem

### ISSUE THREAD

**Issue by DraxoXy** [lucko/LuckPermsWeb#243]
i have a problem with my prefixes were it looks like there are 2 ( over lapped Any ideas why this happens? [https://imgur.com/wBoHt3f](url)

**Comment by BrainStone** [comment]
I don't know how but you messed up linking that image.
Here it is properly: 
![screenshot](https://i.imgur.com/wBoHt3f.png)

Anyways what you see is the normal rendering of text in Minecraft. Every piece of text gets a black shadow. That's why it may look like there are two overlaid.

**Comment by DraxoXy** [comment]
oh ok thank you idk how i messed up the image
