### ISSUE TITLE
Bug on web and on plugin

### ISSUE THREAD

**Issue by diskotekastar** [lucko/LuckPermsWeb#245]
Hi,
I have a problem with luckperms, now after connecting it it erased all my permises and only uuid remained and some players are here more than once.

<img width="150" alt="Capture" src="https://user-images.githubusercontent.com/61634734/82260947-73620280-995e-11ea-9db0-6af63c7f00b9.PNG">

**Comment by BrainStone** [comment]
Update LuckPerms. It has been fixed: https://luckperms.net/
