### ISSUE TITLE
Again the same problem

### ISSUE THREAD

**Issue by diskotekastar** [lucko/LuckPermsWeb#249]
<img width="138" alt="Capture" src="https://user-images.githubusercontent.com/61634734/82313520-c375af00-99c8-11ea-8919-1123c47ca3d0.PNG">

**Comment by Laarryy** [comment]
Have you ensured you're using the latest version from https://luckperms.net

**Comment by diskotekastar** [comment]
Yes, I have the latest version 5.1.20
<img width="143" alt="Capture" src="https://user-images.githubusercontent.com/61634734/82343887-aacebe80-99f3-11ea-9621-d409ff4d65ae.PNG">

**Comment by Turbotailz** [comment]
Please share your editor URL there is not a lot we can do with screenshots

**Comment by TRose2000** [comment]
looks like a offline server to me.
had this issue before my own server was premium (oddline usernames stacks up for some reason)

**Comment by diskotekastar** [comment]
https://editor.luckperms.net/JkhFT9EbjP

**Comment by Laarryy** [comment]
This is a result of poor authentication on a cracked server. The user is being assigned a new UUID everytime they join and the editor therefore has a record for all of those UUIDs. Turning the server to `online-mode= true` would solve this problem.

**Comment by diskotekastar** [comment]
bungeecord or even spigot?

**Comment by Laarryy** [comment]
Just on the proxy. Bungee online mode. And ensure if it is already set, that you have IP-forwarding enabled as well as the `bungeecord` option in every spigot.yml file

**Comment by diskotekastar** [comment]
On bungeecord I have ip_forward: true but on other servers I can't find in spigot.yml ip_forward

**Comment by Laarryy** [comment]
it's only on bungeecord. in spigot.yml the option you need to enable is `bungeecord`

**Comment by diskotekastar** [comment]
I have bungeecord enabled on all servers

**Comment by Laarryy** [comment]
please send a pastebin link containing log files for when the server starts and when the duplicated user joins

**Comment by diskotekastar** [comment]
https://paste.hostify.cz/?5336f1044a84cfc2#J19DrvN4GErgrZH7mDTLzusWvdFqmzxCjBvQCtc48gWN

**Comment by Laarryy** [comment]
You are using JPremium, implying that you are running a network in which players can either directly connect to the backends or bungee online mode is false. Other than that, the player which you are currently experiencing difficulties with used to be connecting while the server had IP-Forwarding set up wrong, but is now connecting with ip-forwarding set up correctly and is receiving their mojang UUID. Try running `lp user <user> clear` for that player and have them connect again. That problem should resolve.

**Comment by diskotekastar** [comment]
I have lockdown activated via the LiteBans plugin, but if I want to grant someone a "litebans.lockdown.bypass" permission, I can't because it's there more than once

**Comment by Laarryy** [comment]
Are they connecting through the proxy

Did you do the command and see what it does?

Will you stop running a server which supports pirates who steal the game?

**Comment by diskotekastar** [comment]
they all connect directly to the proxy, where I have "ip_forward: true" set. I have "bungeecord: true" and "bungee-online-mode: true" set on the servers, and after I used the "/ lp user test clear" command, after the player tried to connect there more than once, the problem was the same

**Comment by Laarryy** [comment]
![](https://i.imgur.com/MvsDEnl.png) 

this seems to suggest one of those things which you say is incorrect

**Comment by diskotekastar** [comment]
These are only players without a purchased minecraft
![image](https://user-images.githubusercontent.com/61634734/82415644-1f980c00-9a79-11ea-981d-a013f6b46d85.png)

**Comment by Laarryy** [comment]
Cracked players (without a purchased minecraft) would be incapable of joining your server if you had bungee online mode set to true and they joined through the proxy

**Comment by diskotekastar** [comment]
So what should I do?

**Comment by Laarryy** [comment]
Set bungee-online-mode to true, firewall the backends, and run the command I gave you for all users that joined before you did.

**Comment by diskotekastar** [comment]
I have bungee-online-mode true https://paste.hostify.cz/?d4d207bf4f227395#Gqqqi7daB8UEN3XgHwNTrfXKZWz9UjEk2zHvHPD9wn8x

**Comment by diskotekastar** [comment]
and would it help if I connected it to RedisBungee?

**Comment by Turbotailz** [comment]
I'm going to close this as the issue has nothing to do with the editor.

If you need help with setting up your network I can suggest joining communities such as [Admincraft](https://reddit.com/r/admincraft) which are better equipped at helping people with more general Minecraft related issues..
