### ISSUE TITLE
Change permissions that end in .info to not be autolinks

### ISSUE THREAD

**Issue by Laarryy** [lucko/LuckPermsWeb#250]
![](https://i.imgur.com/wu6g9aD.png)
The Permissions page is full of these shiny green things

**Comment by Turbotailz** [comment]
Opened an issue on the dependency to see if there is an easy solution before I go digging, lol
markdown-it/markdown-it#674

**Comment by Tobi406** [comment]
https://github.com/markdown-it/markdown-it#linkify

We can maybe just turn off links for the `.info` tld? No idea how the linkify object tough

**Comment by BrainStone** [comment]
Better to turn it off entirely. There may be other permissions that end in a tld.

**Comment by Tobi406** [comment]
Just removing the option in `vue.config.js` seems to work. 

Links like `https://luckperms.net` don't get parsed any longer, but `[https://luckperms.net](https://luckperms.net)` still works.

**Comment by BrainStone** [comment]
Oh. That is on the wiki. My bad.

I think having an option to require the protocol prefix should be enough then.

**Comment by Turbotailz** [comment]
Yeah markdown links will still work and I guess we could just rely on making sure all links are set like that.

**Comment by Tobi406** [comment]
https://github.com/markdown-it/linkify-it#api

The `fuzzyLink` option may also work (altough I still don't have any idea on how to access the linkify object in the chain config.

**Comment by lucko** [comment]
Recently fixed in the last batch of changes :)
