### ISSUE TITLE
default role not being given upon new player joining

### ISSUE THREAD

**Issue by calamityy** [lucko/LuckPermsWeb#256]
I've got a default role on luckperms to be auto-assigned to players when they join my server to allow basic commands, I'm aware this should happen but it seems I possibly deleted the original default role and now nothing is assigned when a player joins- they have no role unless manually given. I've looked on the wiki post about it, googled/searched on GitHub, and looked in the config, but I can't find any solutions.
Can I ask for any suggestions on how to fix this please?
Thanks in advance

**Comment by Tobi406** [comment]
Did you "made" the default role? How?

**Comment by calamityy** [comment]
I can't remember if I made another group called 'default' or it is the original group from the luckperms was first loaded

**Comment by calamityy** [comment]
Sorry for wasting your time, I think everything's fixed now after some changes done
Thankyou for your help though!

**Comment by BrainStone** [comment]
"I fixed it after doing some stuff" without explaining what you did is quite rude.

**Comment by calamityy** [comment]
I changed the weight and asked a new player to join and test if it auto assigns the role, as it didn't do it when one player joined, but for someone else it did, so it must've been a mistake I made.

 I didn't mean to be rude
