### ISSUE TITLE
Fix Download Suggestion Feature

### ISSUE THREAD

**Issue by JasonHorkles** [lucko/LuckPermsWeb#257]
The new site is nice, but the feature that suggests what version of LuckPerms you should download needs a little change. It should have some sort of note or something regarding the proxy version saying that you also need to install LP on the backend servers like [the wiki says](https://github.com/lucko/LuckPerms/wiki/Network-Installation#the-bungeecord-version-of-luckperms) so people don't get confused
![image](https://user-images.githubusercontent.com/51760372/82507057-84c22080-9abe-11ea-8528-daa2fc011be1.png)

**Comment by BrainStone** [comment]
Also the 1,7,10 support when using Travertine should be mentioned. Kinda like it is with Bukkit Legacy.
