### ISSUE TITLE
Add ability to see offline players and to add permissions to them in the editor.

### ISSUE THREAD

**Issue by benrobson** [lucko/LuckPermsWeb#264]

**Comment by Turbotailz** [comment]
This should already be happening, what version of LP are you using?

**Comment by benrobson** [comment]
Running LuckPerms v5.0.39

**Comment by Laarryy** [comment]
Update at https://luckperms.net for sure - also, if they're in default group they may not appear - you can make them appear in your next editor session by adding something to them ingame, like `lp user <user> permission set test.test`
