### ISSUE TITLE
problems with luckperms self hosted

### ISSUE THREAD

**Issue by lastsamurai26** [lucko/LuckPermsWeb#279]
I'm afraid I'm a little annoyed.

In the meantime I have managed to build the new website for the LP with Nodejs and npm after feeling like 320 tries.

i have also entered the appropriate URL in the config.yml, but each time i get a 404.

With the command "npm run build" I get an error that I should do "npm update" and "npm audit fix" but I don't get it.

what else could it be?
What information do you need.

I just want the editor, verbose and tree, that's all I need.

**Comment by Turbotailz** [comment]
Have you set up your webserver to server the generated files?

Really need more info on what your setup is and exactly what you've tried.

**Comment by BrainStone** [comment]
The two npm commands can be ignored.  
Also did you try to run the installer?

**Comment by lastsamurai26** [comment]
I've made it now, after using the installer I've broken the settings of my web server.

I have taken the installer complete apart and only made the settings I need, but I noticed that the readme of the htaccess is missing so it didn't work for me.

**Comment by BrainStone** [comment]
What readme are you talking about?
I can't quite follow you.

And if you want me to take a look at the issue with the installer I need a tad more info.
Like what webserver, what broke, what OS, etc.

**Comment by lastsamurai26** [comment]
I used this readme 
https://github.com/lucko/LuckPermsWeb/blob/master/installer/README.md

and I took apart the installer (https://github.com/lucko/LuckPermsWeb/blob/master/installer/install.sh) and found the following file https://github.com/lucko/LuckPermsWeb/blob/master/installer/files/apache/luckpermsweb_footer.conf

and that's how I got everything going.

**Comment by BrainStone** [comment]
Well, the readme mentions nothing about the .htaccess, because it doesn't ever use one. And yes that's part of the config.

You still haven't told me how it broke your webserver.

**Comment by lastsamurai26** [comment]
i first used the installer and the installer did something i can't explain. Something the installer did, I don't know what, but I had to rebuild my VM, because I tested it in a VM for safety reasons.

I got a 500 http error after the vhosts brought by the installer were activated.

**Comment by BrainStone** [comment]
Well, do you have logs?  
And still not much info.

**Comment by lastsamurai26** [comment]
unfortunately no, in my VM the logging was not active.

But as soon as I have time, I can test it again and open a new ticket if necessary, but this one can be closed for now
