### ISSUE TITLE
Problem with the player's UUID

### ISSUE THREAD

**Issue by diskotekastar** [lucko/LuckPermsWeb#281]
Hello,

I have a problem with the player's UUID, the UUID is separated from the player and permissions remain on it.

Thank you for the advice

![image](https://user-images.githubusercontent.com/61634734/85069948-426f2a80-b1b5-11ea-8ecc-a2e93a2efae3.png)

LuckPerms editor:
https://luckperms.net/editor/LHQYYC4Sbt

config.yaml (bungeecord):
https://paste.hostify.cz/?e8619c19ca1c1116#39V1Yt5gncnNyPCWDJMuahrNRKt3N2YCos2SD2VFq3RE

config.yaml (spigots servers):
https://paste.hostify.cz/?3449e1f0e8447300#HeESkT3Bz8vXHuyryUBg7d8grAetUw4MZ5guRsck3KRf

MySQL files:
https://www.mediafire.com/file/tcvo1z8l6e6cazv/db_25709_luckperms2.zip/file

Warn from console:
https://paste.hostify.cz/?5c6856ae6e942ba5#FnhJhe52t9bkvGAZsRDVG6VQTj18BL3psSyPMgPfhU3G

**Comment by diskotekastar** [comment]
And duplicate players name 
![image](https://user-images.githubusercontent.com/61634734/85117797-b5ad8680-b21f-11ea-93ca-fe64440245b3.png)

**Comment by Turbotailz** [comment]
Please update to the latest version of LP from https://luckperms.net/download

**Comment by diskotekastar** [comment]
I have the latest version of LP 5.1.55

**Comment by Turbotailz** [comment]
This is more of an issue with your setup of server or LuckPerms (or both) and not the editor so would be better to open this issue on lucko/LuckPerms after updating to the latest version and confirming the problem is still persisting.
