### ISSUE TITLE
Web Export Feature

### ISSUE THREAD

**Issue by Laarryy** [lucko/LuckPermsWeb#286]
Instead of saving just recent changes, add a button which uploads everything to bytebin, probably as a recent change in entirety so that luckperms plays nicely with it. This would be very useful for exporting where FTP is unavailable etc and would allow people to restore their servers in an emergency rather easily with an editor link if backups unavailable. 

Note: I've noticed that you're probably going to have to add the creation of the groups to the bytebin because simply marking everything in a standard bytebin as a change doesn't include the groups.

<3 Turbo

**Comment by Turbotailz** [comment]
fixed in https://github.com/lucko/LuckPerms/commit/a766c0e9aa31789524abcc4e264eee76e9bee603
