### ISSUE TITLE
Editor doesn't list all the permission nodes or indicate "enabled/disabled"

### ISSUE THREAD

**Issue by smmmadden** [lucko/LuckPermsWeb#29]
The LuckPerms editor provides all the permissions in an ordered way by priority which is not ideal for an editor, but it does work.

The top header where you can search for Permission, Expiry etc can be used to get a true sorted list of permissions or find one in the list. However, there appears to be two problems with using drop down.

The list is showing permissions (I'm assuming) that the list is both available to set, and already set which makes it a bit more difficult to know by looking which is or isn't set. Adding a visual indicator (*, color or even a second column in the results) clearly showing which permission node is already set would be a plus!

The second problem with the Permission drop down is it does not list all the results for servers that use a lot of plugins. One of my servers has 51 plugins from A - W, but there must be some limit restriction being imposed on the results. For mine, it stopped in the M's and I have many more after that. It's possible that the query is limited to 500 results, which is fairly common for database apps but this list should always show all of them or include some pagination for performance reasons.

**Comment by lucko** [comment]
The dropdown completion menu is provided by your browser, not editor code.

Not much I can do if it's being limited.

**Comment by smmmadden** [comment]
how can the browser limit what I see in a drop down of values set by the server?  That's not how drop downs behave.  There isn't any configuration in any browser that I ever heard of that allows users to display more or less.  To be clear, this is what I'm referring to.  The drop down for Permission is the header you built to hold all the permission nodes - nothing I've done to make it work. :-)
![image](https://user-images.githubusercontent.com/10309346/33973045-b9324d5e-e04e-11e7-876b-273b7a7a70b8.png)

**Comment by lucko** [comment]
If you’re such an expert, you tell me what’s wrong.  :)

**Comment by smmmadden** [comment]
I did in my original post.  Check how the html is created for the Permissions column and the data that is being sent.  Does it include all data from the table or is it restricted to say a certain count (e.g. 100, 250, 500, etc).  The overall html page shows all the data fine, it's only the column header that is limiting the results. :-)

**Comment by lucko** [comment]
> The dropdown completion menu is provided by your browser, not editor code. Not much I can do if it's being limited.

**Comment by smmmadden** [comment]
I guarantee that this isn't a browser issue.  I've been writing HTML for 20+ years and built hundreds of websites.  :-)  Look at the object that you are passing into the select field.  
<div id="inpform">
 **<input type="text" list="permissions-list" name="permission" placeholder="Permission">**
 <input type="text" name="expiry" placeholder="Expiry">
 <input type="text" name="server" placeholder="Server">
 <input type="text" name="world" placeholder="World">
 <input type="text" name="contexts" placeholder="Contexts">
 <i class="clickable material-icons add" title="Add">add_box</i>
 </div>

Where is the data coming from for all the permission nodes?  I can see permission nodes that are not in the main table which to me implies this is coming from code checking each plugin for valid permission nodes to include.  It seems to stop iterating over all the plugins that I have.  It stops at gadgetsmenu as you should be able to see here: https://lpedit.lucko.me/?945be3b63f018d69965a912fa991ba12/6a27493d6b1a39168e497b95e231a69386ad3162

Given that the perms are sorted, you must have a routine that is getting the list of plugins, iterating over each to get their permission nodes and then storing them in this list of results for the input statement.

Does that help at all?

**Comment by lucko** [comment]
Nope - as you can see, all of the data is included in the payload.

https://gist.githubusercontent.com/anonymous/945be3b63f018d69965a912fa991ba12/raw/6a27493d6b1a39168e497b95e231a69386ad3162/luckperms-data.json

**Comment by lucko** [comment]
These values are simply iterated when the payload is read and added to the datalist.

https://github.com/lucko/LuckPermsWeb/blob/master/assets/app.js#L723-L726
https://github.com/lucko/LuckPermsWeb/blob/master/assets/app.js#L86-L90

**Comment by lucko** [comment]
Just done some testing of my own - all of the values are there, but as I've been saying all along, only some are displayed in the drop down.

Ordinarily, only values up until `essentials.spawnerconvert` are displayed
![](https://luck.sh/d2Kta5QDEb4mHTxEp_XhwUHABEE=)

But if you then begin typing in more characters, more of the data shows.
![](https://luck.sh/0PR_sbYWrpeZWG_Ar2qkaetc40A=)


Soo, once again:

> The dropdown completion menu is provided by your browser, not editor code. Not much I can do if it's being limited.

**Comment by smmmadden** [comment]
Thanks for testing.  The end result is that because there can be a very long list due to the number of plugins a server has, the attribute "list" or "datalist" are not recommended due to each browser not properly handling the content. So yes, technically it is the browser that is "causing the limited results" but it isn't anything that a customer can fix.  If you scroll to the bottom of the article, you'll see all the browser that "lack support of this attribute".  That's what I rely on when writing HTML5 - making sure all the browsers can take advantage of what I provide.  See source: https://html.com/attributes/input-list/ 

At least there is a semi workaround for it by typing in the last permission shown in the list and hope that you can get the next page of results.  So with 50+ plugins, that's a lot to go thru.  Please consider the request as an enhancement.

**Comment by lucko** [comment]
I played around with a number of 3rd party libraries before setting with the native HTML5 option. In my experience a lot of the 3rd party libs were glitchy and required a lot of work to get them working correctly.
