### ISSUE TITLE
Limit on number of nodes in "Add Permissions" list

### ISSUE THREAD

**Issue by blindcat97** [lucko/LuckPermsWeb#292]
The drop-down list that appears when you go to add permissions has all of the (previously checked) nodes listed, but because of a couple plugins with an extreme number of node options (in this case mainly Citizens and Essentials), I'm not able to view the entire list. In my case, I can only get about halfway through the list of Essentials nodes, mostly because of the `essentials.hat.prevent-type` category which includes a node for basically every item in the game. I would personally really appreciate either a longer list (or some way to paginate it, perhaps?) or a way to essentially "blacklist" certain nodes from appearing in the autocomplete list. For example, I'd want to hide `essentials.hat.prevent-type.*` as well as a few Citizens categories. As it stands, I'm having to reference a tree and manually enter any perms I want after the cutoff, which is quite a few and a real pain.

Thank you for the editor though and for any help!

**Comment by BrainStone** [comment]
Well start typing and only what matches what you wrote stays in the list @blindcat97.

**Comment by blindcat97** [comment]
Obviously, but when trying to click multiple items, the list resets if you were typing vs if you just scrolled to that area. That means that adding multiple similarly named is extremely tedious. Not to mention it's still a huge pain to have to cross reference a tree for everything after a certain point when before that i could just scroll and click what I needed.

I just spent 2 hours adding perms like this, I'm pretty aware of the basic shortcuts, but there's only so much it can do. It was just a suggestion.

**Comment by Turbotailz** [comment]
Can you provide a video/gif maybe of what you're experiencing? It's a bit hard to understand via text.

**Comment by blindcat97** [comment]
So sorry for the long delay; I've been away from home. Here's a gif: basically, after a certain point, I just can't scroll any further.

![troubleshooting](https://user-images.githubusercontent.com/13594367/88836099-3444fe80-d1a4-11ea-9ec2-a56cd7a998e1.gif)

It's pretty clearly due to the absolutely insane number of permissions nodes under essentials.hat.prevent-type. I'm going to introduce an issue with essentials that there should probably be a setting to stop it from generating something like 2500 unnecessary permissions, but I thought the issue was worth bringing up here too, as there's likely other circumstances where people might run into problems.

**Comment by Turbotailz** [comment]
Could you send a link to your editor please?

**Comment by blindcat97** [comment]
https://luckperms.net/editor/YpfpuX1jyv

**Comment by Turbotailz** [comment]
Okay, so the issue here is actually that the dropdown plugin I'm using here defaults to showing only 1000 options (which seems like a sane amount, tbh).

If you check the raw data that gets sent to the editor (https://bytebin.lucko.me/YpfpuX1jyv), you'll see under `knownPermissions` that there are in fact more than 1000 nodes available.

You can filter the list by simply typing any string of text and the list will update in real time. I don't think increasing the limit is a very good idea at this point when there are other ways of getting the permissions you are looking for.

**Comment by blindcat97** [comment]
That's reasonable. Essentials reported that they're likely to remove this permission group anyway.
