### ISSUE TITLE
Browser lag when using lp tree

### ISSUE THREAD

**Issue by 04fsnape** [lucko/LuckPermsWeb#295]
Hello,

Running `lp tree . <username>` results in the browser lagging, and on Firefox it said "A web page is slowing down your browser".

It just shows 
![image](https://user-images.githubusercontent.com/33752988/87954791-610a5f00-ca9c-11ea-9fd6-0ef0618270a3.png) (firefox)

or 
![image](https://user-images.githubusercontent.com/33752988/87954845-7089a800-ca9c-11ea-9aee-92a8c8e1f28e.png) (chrome, edge)

If you go to the network tab you can find the HTTP response which has the JSON data, but it's not being rendered properly in the browser.

**Comment by Turbotailz** [comment]
Can't do much without the URL

**Comment by 04fsnape** [comment]
> 
> 
> Can't do much without the URL

https://luckperms.net/treeview/jtuF64gnIp

**Comment by Turbotailz** [comment]
`Maximum call stack size exceeded` error in the console. I will have to do some debugging on this issue but won't be able to get to it for a while.

Thanks for reporting.

**Comment by BrainStone** [comment]
Well keep in mind the links are deleted after a week.

**Comment by Turbotailz** [comment]
I know that :P I meant I'm at work, will look at it later today.

**Comment by Turbotailz** [comment]
Disregard that last message, I need a new link please @04fsnape
