### ISSUE TITLE
Question: Self hosted editing MySQL Directly 

### ISSUE THREAD

**Issue by FrozenBeard** [lucko/LuckPermsWeb#300]
Ahoy

I just found out you can self-host the LuckPerms Web UI, which would mean we could just plug in our MySQL details and use the editor directly with the MySQL table without need for the commands in game to generate URLS for temporary pastebins of the permissions. Is this how it works at present? or does it just duplicate the current method of Log into Minecraft > Run command > Open Website in browser & make changes, Copy URL back in-game?

**Comment by Turbotailz** [comment]
Self-hosting the web interface just lets you point the editor/other tools to your own domain, it does not enable any new functionality between the UI and the plugin.

**Comment by FrozenBeard** [comment]
Shame, it could work like phpMyAdmin with permissions.

**Comment by BrainStone** [comment]
Not really. The editor works without any backend logic. Meaning that you can't connect to a database server. Or if you could and wanted to preconfigure the database details you'd send them over the internet.

As mentioned before I've been toying with the idea of creating an extension for LP that allows the edtior to work live on the data. The main issue here being security.

**Comment by FrozenBeard** [comment]
But it would improve it drastically fixing the bad workflow at present, if you have a web application running locally, why on earth would you choose to send data to a remote server to then pull the data into the web application when you have direct access via the database! Flawed design, it requires extra steps.

The fact you are using nodejs means you are fully capable of making database queries.

**Comment by lucko** [comment]
The vast majority of our users have no means or desire to self-host the editor, hence the current centralised design. I do not see it as a flaw.

**Comment by BrainStone** [comment]
> If you have a web application running locally, why on earth would you choose to send data to a remote server to then pull the data into the web application when you have direct access via the database! Flawed design, it requires extra steps.

Considering it would require significant effort to implement it, require a locally running node instance (the current editor works with static files only and only needs node to generate those files) and it would now only support a single storage type I can very much see why this hasn't been tackled.  
My proposed solution with an extension to LP would be better. As that would have all the upsides you have with the current editor design (static web files only, support for all storage options) and would need only one additional port the MC server needs to be able to listen to.

**Comment by FrozenBeard** [comment]
Yeah definitely out of scope of your user base, but requested as an alternative to the symbolic links if I were required to use this workflow.
Looks like the Symbolic link issue was fixed, so I will be able to use that.

**Comment by BrainStone** [comment]
I'll say it again: If you're working so much on permissions that opening an editor session is a significant slow down in your workflow, you should consider using a developement server instead of doing everything live.
