### ISSUE TITLE
Tree viewer won't load when defining both scope and player.

### ISSUE THREAD

**Issue by Fefo6644** [lucko/LuckPermsWeb#302]
When running `lp tree` and filling in both scope and player, it just shows what's below.
The data is uploaded correctly to bytebin, yet the tree viewer won't display anything other than this.

![](https://media.discordapp.net/attachments/241667244927483904/743919489992622161/unknown.png)

If I don't fill in the player field, it loads correctly tho.

**Comment by BrainStone** [comment]
What's the exact command you used?

**Comment by Fefo6644** [comment]
From console: `lp tree quests Fefo6644`
[bytebin](https://bytebin.lucko.me/HColUXNTrQ) and "[treeview](https://luckperms.net/treeview/HColUXNTrQ)"

**Comment by BrainStone** [comment]
That's the JS error: 
![grafik](https://user-images.githubusercontent.com/4106544/90303734-d22d0e80-deb0-11ea-945f-6fadb5de5758.png)

**Comment by Turbotailz** [comment]
Errors are obfuscated in production, I can see what the problem is in the dev version. Should have a fix for it shortly :)
