### ISSUE TITLE
Permission Expiry Bug

### ISSUE THREAD

**Issue by Nisutec** [lucko/LuckPermsWeb#304]
Hello,
If a permission has already a expiry date and you try to change this date the date selector will start at Jan 1970 and not at the current date of expiry. If a permission has no expiry date the date selector will work perfect.

https://drops.n-tp.de/o0u8q7mE

**Comment by Turbotailz** [comment]
Should be fixed in https://github.com/lucko/LuckPermsWeb/commit/95a01af4d81470f1b95ef3cb2618b1979bb597f4
