### ISSUE TITLE
better support for values other then true/false

### ISSUE THREAD

**Issue by ryantheleach** [lucko/LuckPermsWeb#305]
Currently the Web is optimized for true/false values which is great! 99% of the time.

Adding permissions/meta/options with values other then true/false is mildly painful.

**Comment by Turbotailz** [comment]
Could you give an example please?

**Comment by ryantheleach** [comment]
I think I made a crucial mistake when making this. 
I'm a little rusty on LuckPerms and thought the value was supposed to be the 'data' contained for the meta.
