### ISSUE TITLE
Context menu appearing behind "Permission nodes" header

### ISSUE THREAD

**Issue by JasonHorkles** [lucko/LuckPermsWeb#309]
If you add a lot of contexts to a permission node towards the top of the page, it will end up looking like this
![image](https://user-images.githubusercontent.com/51760372/92201077-c346d580-ee38-11ea-82a1-bd2af965d7af.png)
preventing the top from being visible

**Comment by Turbotailz** [comment]
Thanks. It's not a very easy fix so I can't say when I'll have it fixed.

In the meantime, consider sorting the nodes so the node you're trying to edit doesn't appear at the top.
