### ISSUE TITLE
Mark newly added permission

### ISSUE THREAD

**Issue by Phoenix616** [lucko/LuckPermsWeb#31]
Currently the only way to see which permission was added is by remembering which the last one was and see which are below it. It would be nice to indicate this a bit better, e.g. via a different colored background or some icon?

**Comment by lucko** [comment]
Yep, agreed.

Maybe we could take some inspiration from the way GitHub handles things.

![](https://luck.sh/Cb4ZT3sHugF1M51IF5A0QPZxbYQ=)

**Comment by Phoenix616** [comment]
Yeah, that would probably look nice too.
