### ISSUE TITLE
The new look is too zoomed for 1366x768 diplays

### ISSUE THREAD

**Issue by cluser404** [lucko/LuckPermsWeb#310]
I appreciate the latest UX imrovement on the luckperms webeditor.
But the UI is too zommed for 1366x768 displays.
I am able to see only 4 nodes at a time.
which is frustating.
Please solve these issue by rearranging some components.

Best wishes :)

**Comment by Turbotailz** [comment]
There is a breakpoint at 1300px width which makes the font size larger, your resolution is just over that, so you could simply resize the window to be 66 pixels narrower :P 
Alternatively, hit `ctrl -` to zoom out the browser window which should resize everything properly.

**Comment by cluser404** [comment]
> There is a breakpoint at 1300px width which makes the font size larger, your resolution is just over that, so you could simply resize the window to be 66 pixels narrower :P
> Alternatively, hit `ctrl -` to zoom out the browser window which should resize everything properly.

So isn't it possible for the devs to add padding to 
the webapp to resize everything properly.

**Comment by cluser404** [comment]
Setting the font size to 0.9rem on that breakpoint fixes it.

but I cant find `@include breakpoint($lg)` on common scss
mostly because I am a noob coder.

can you fix it please

![image](https://user-images.githubusercontent.com/30370919/92258434-ab368b00-eef8-11ea-879b-0f64a32bd678.png)
![image](https://user-images.githubusercontent.com/30370919/92260231-64956080-eef9-11ea-981a-445af250d0e6.png)

**Comment by Turbotailz** [comment]
@cluser404 could you check if this is better for you?

https://deploy-preview-334--luckperms.netlify.app/editor/demo

**Comment by cluser404** [comment]
thanks dev.
you are cool
