### ISSUE TITLE
Allow user deletion

### ISSUE THREAD

**Issue by Laarryy** [lucko/LuckPermsWeb#311]
Suggestion: Make a neat little murder button on the user sidebar and top bar when a user is selected to vaporize them from the server once the session is applied (lp user <name> clear but webeditor) 

<3

**Comment by Timmy109** [comment]
Don't know why this hasn't been implemented sooner with all the requests for support regarding deleting users from a database.

**Comment by Turbotailz** [comment]
> Don't know why this hasn't been implemented sooner with all the requests for support regarding deleting users from a database.

I have to check with @lucko first whether or not it can actually be done, so this may have to wait until the functionality is present in the plugin.

**Comment by Turbotailz** [comment]
Luck added this functionality in the plugin for version `5.1.105` - https://github.com/lucko/LuckPerms/commit/971bb67b5158894308ca0bd89928bf070e125a68

**Comment by Turbotailz** [comment]
Added in https://github.com/lucko/LuckPermsWeb/commit/18c98b94e60f2888bb2705a5027ed8c943196766
