### ISSUE TITLE
Search highlight disappears while scrolling

### ISSUE THREAD

**Issue by christaylor201** [lucko/LuckPermsWeb#313]
After the latest update, search highlight disappears while scrolling, see [the video](https://streamable.com/cp8e9o). It's pretty annoying since I search for permissions almost all the time.

I use Google Chrome version 85.0.4183.102.

**Comment by Turbotailz** [comment]
Yeah this was a side effect of the improvement I made to groups with really large sets of nodes.

Don't worry I will add a proper search feature in the future 

In the meantime you could use this tool I made to search for permissions in your setup: https://lp-search.turbotailz.com

**Comment by christaylor201** [comment]
> Yeah this was a side effect of the improvement I made to groups with really large sets of nodes.
>
> Don't worry I will add a proper search feature in the future

Nice to hear, I'm looking forward to it.

> In the meantime you could use this tool I made to search for permissions in your setup: https://lp-search.turbotailz.com

Oh, thank you very much! I'll definitely use this until the in-built search feature comes out.
