### ISSUE TITLE
Contexts not working

### ISSUE THREAD

**Issue by theplacer** [lucko/LuckPermsWeb#330]
Hi, I keep having issues with luckperms where the contexts aren't working. I configured everything correctly including the server name and the contexts just aren't working. The permissions do not work on the specified worlds/servers. How do I fix this?

**Comment by Laarryy** [comment]
Please follow the issue template. 

Also, if I told my doctor I just 'wasn't working' they would have no idea what was wrong or how to even start helping - please be specific in describing your problems; what have you tried, and what part of the process that you expect to work breaks first? Also have you created and used a database for syncing your perms across servers and then tried applying context, or are you using local storage.

Screenshots of `lp info` on all servers and `lpb info` on your bungee (or `lpv info` if you use velocity) would be appreciated, as well as a copy of your config, passwords removed if there are any. Use https://paste.lucko.me or https://bytebin.lucko.me or similar to send the config.

**Comment by Laarryy** [comment]
Also, why is this issue on the website repo? I just noticed - this should be on lucko/LuckPerms as it has nothing to do with the site

**Comment by theplacer** [comment]
Sorry, my server provider linked me to this github page. 

About the issue:
I have tried adding the server and world permissions to some of my permissions. I was sure that the permissions were correct. Once I added the contexts, the permissions stopped working. But when I removed the contexts, the perms stopped working. The part of the process that breaks first is the permissions when I add the contexts to them (the world and server contexts) I have a MySQL database for my server that I use for perms, but I use pluginmsg for my messaging service. I use mysql for storage.

![Screen Shot 2020-10-16 at 10 39 48 AM](https://user-images.githubusercontent.com/72987400/96279185-f635ca80-0f9b-11eb-85df-fec0c93245aa.png)
![Screen Shot 2020-10-16 at 10 40 29 AM](https://user-images.githubusercontent.com/72987400/96279257-077ed700-0f9c-11eb-92ed-6355d827b6be.png)
![Screen Shot 2020-10-16 at 10 38 43 AM](https://user-images.githubusercontent.com/72987400/96279024-
![Screen Shot 2020-10-16 at 10 41 18 AM](https://user-images.githubusercontent.com/72987400/96279340-267d6900-0f9c-11eb-9e94-dd485e83ac28.png)
![Screen Shot 2020-10-16 at 10 42 30 AM](https://user-images.githubusercontent.com/72987400/96279465-4f056300-0f9c-11eb-876d-2c9f278dd283.png)

cedefd80-0f9b-11eb-9f49-7b365c76f2e6.png)
![Screen Shot 2020-10-16 at 10 39 17 AM](https://user-images.githubusercontent.com/72987400/96279099-def6dd00-0f9b-11eb-98cf-75c60f5b0efc.png)

 As requested, here's the bungeecord luckperms config: https://paste.lucko.me/sjSAOup0dx

**Comment by Fefo6644** [comment]
You need all servers to have the same `messaging-service` in LP config (that includes bungee LP), I suggest you set them all to `sql` and also set `sync-minutes` to `-1` in all LP configs (including bungee LP). Once you do that, restart every server. See if the issue still persists.

**Comment by theplacer** [comment]
Ok

**Comment by theplacer** [comment]
It works now, I just realized that I can only have 1 server context per permission or it will not work
