### ISSUE TITLE
Search query doesn't return anything

### ISSUE THREAD

**Issue by christaylor201** [lucko/LuckPermsWeb#337]
I was looking forward to the new search function, however if I try to search anything, it will result in an exception:
```
vue.runtime.esm.js:1888 TypeError: e.context[t].some is not a function
    at SearchNodes.vue:66
    at Array.some (<anonymous>)
    at SearchNodes.vue:66
    at Array.filter (<anonymous>)
    at a.results (SearchNodes.vue:55)
    at nr.get (vue.runtime.esm.js:4479)
    at nr.evaluate (vue.runtime.esm.js:4584)
    at a.results (vue.runtime.esm.js:4836)
    at a.groupedResults (SearchNodes.vue:72)
    at nr.get (vue.runtime.esm.js:4479)
oe @ vue.runtime.esm.js:1888
```

**Comment by Turbotailz** [comment]
I need more info than that. Please provide your editor URL and the
query/queries that you've tried.

**Comment by christaylor201** [comment]
Here's [a link](https://luckperms.net/editor/Ce2Zph154x) to the editor.

These are the queries which I've tried:
* `a`,
* `multiverse`,
* `vip`,
* and so on (any words or letters).

**Comment by Turbotailz** [comment]
Should be fixed with https://github.com/lucko/LuckPermsWeb/commit/4019812490a3e1f3662a2a778c0c8b18b3df9bd7

**Comment by christaylor201** [comment]
Thank you for the lightning fast fix!
