### ISSUE TITLE
Update file locations for LuckPermsWeb for Nginx v1.19.x

### ISSUE THREAD

**Issue by kokomo123** [lucko/LuckPermsWeb#344]
Nginx changed the file locations for vhost files. Now it has to go on to /etc/nginx/conf.d. /etc/nginx/sites-enabled might still work, but on a fresh install it is deprecated and doesn't exist within /etc/nginx anymore. Whenever i try to update the locations to the new one, it errors out and no luckpermsweb nginx .conf is generated, probably due in part it cannot find everything it wants or my lack of understanding in the install.sh, i can upload a log which i will do so now. 
https://bytebin.lucko.me/1in6T7Mxk0

**Comment by BrainStone** [comment]
Well that is an issue, because many server distros will not get that version in years.

I'll need to think about what to do. If you maybe can find a way to tell if I'm supposed to use the old or new versions, let me know.

Btw if you could provide a change log note about that change that would be aweosme!

**Comment by BrainStone** [comment]
Interestingly enough I can't find any errors related to nginx in your log.

**Comment by kokomo123** [comment]
No errors, eh? weird. well right now the current version is fine, just with the new versions above v1.19 are affected, so it shouldn't break anything. I don't believe they've updated apt in a while but if you add their repo you will get the mainline version.

**Comment by kokomo123** [comment]
https://stackoverflow.com/questions/17413526/nginx-missing-sites-available-directory and https://stackoverflow.com/questions/41303885/nginx-do-i-really-need-sites-available-and-sites-enabled-folders. It doesn't seem to come with those directories by default, but ubuntu and debian does, so i'm wondering if they aren't deprecated after all?

**Comment by BrainStone** [comment]
Note the question you linked is about CentOS. Which never had these directories afaik. They always used that system.

**Comment by kokomo123** [comment]
Well, my mistake then. I'm still clueless on this format, because https://nginx.org/en/CHANGES says nothing about this directory format.

**Comment by BrainStone** [comment]
Well the format is typically defined by the mainters for the specific distro. That's for example why it's different on CentOS.

**Comment by kokomo123** [comment]
I see, so i'm assuming this format may not be necessary? I see what you mean then :/ i guess i bamboozled us both

**Comment by BrainStone** [comment]
Frankly I don't even know what the issue is you came here for. I couldn't see any issues in your log.
And as of now the CentOS directory format is not supported for the script.

It works well with Ubuntu and Debian and similar distros.

**Comment by kokomo123** [comment]
Well, i proposed this issue thinking it would probably shed light to the latest version of nginx, but I suppose then i would need to create the directory manually and fix it that way. 👍🏻 Issue resolved, sorry about this then.
