### ISSUE TITLE
Verbose viewer stacktrace

### ISSUE THREAD

**Issue by lucko** [lucko/LuckPermsWeb#348]
The stacktrace should ideally be a single `<code>` block with newlines between each line instead of a list of individual code blocks.

Like this

```html
<code>line1
line2</code>
```

instead of this

```html
<ul>
  <li>
    <code>line1</code>
  </li>
  <li>
    <code>line2</code>
  </li>
</ul>
```

I've tried to do this a few times, but couldn't figure out the CSS to get whitespace/word wrap to work properly :((

**Comment by BrainStone** [comment]
I was gonna say use the `<pre>` tag but it seems like someone beat me to it. With even a PR
