### ISSUE TITLE
Unable to investigate individual player permissions due to 500 player limit in webeditor

### ISSUE THREAD

**Issue by oranges13** [lucko/LuckPermsWeb#354]
Hello! Due to the limit of 500 players in the webeditor, we are unable to investigate individual player permissions. I totally understand why this limit was imposed due to optimization needs, but I feel like searching for a player in the sidebar should appropriately filter the list based on available players which may not be shown initially.

Is it possible to revise the way the search works so that we can see players which may not be included in the initially loaded 500? Thank you.

**Comment by Turbotailz** [comment]
I believe you can open an editor session for a specific player by doing /lp user (user) editor
