### ISSUE TITLE
Can't delete user form /lp user <> editor

### ISSUE THREAD

**Issue by Xaver106** [lucko/LuckPermsWeb#359]
Deleting a user in his web editor, opening it via `/lp user <name> editor`, is not possible, as the editor goes into an infinity loading screen.

https://user-images.githubusercontent.com/46501008/118640064-d9cf6a00-b7d8-11eb-805f-8070e1bf81e0.mov

The Loading screen goes on forever.

LP Version 5.3.0

**Comment by Turbotailz** [comment]
Could you please send your editor URL

**Comment by Xaver106** [comment]
Sure: https://luckperms.net/editor/keRA005aGX

**Comment by Turbotailz** [comment]
Thanks. Pretty sure I know why it does this. Will try make time to fix it later.

In the meantime, you can clear the user's data with a command `/lp user <user> clear`
