### ISSUE TITLE
Undo is a must have. button or CTRL+Z

### ISSUE THREAD

**Issue by SpecifiedNull** [lucko/LuckPermsWeb#361]
There have been countless occasions where I really really needed to undo some changes after editing the permissions for hours. then just 1 mistake (selected checkbox to select all perms accidentally) changed entire permissions and I had no choice than to generate the editor link again to redo everything I did for the past hour. other alternative would be check thousands of permissions and fix them again.
I mean Undo is a must have in any sort of application or editing software/web we make mistakes. did you assume we never make mistakes? maybe you never do. so I challenge you, when you code plugins, never use undo button or ctrl+z when you code luckperms plugin. see how you can do this. good luck !

**Comment by BrainStone** [comment]
Duplicate: https://github.com/lucko/LuckPermsWeb/issues/133

**Comment by Turbotailz** [comment]
As BrainStone said, there is already an issue open to track this. It has been worked on but I found it really difficult to implement so I put it on hold.

I also wanted to point out your condescending tone is really not welcome in the open source community. The way you word things here, doesn't make me want to do it. Just saying. Maybe work on that next time you want to suggest a feature.
