### ISSUE TITLE
Players have all permissions

### ISSUE THREAD

**Issue by M4rtyn4** [lucko/LuckPermsWeb#364]
Recently updated server to 1.17 and everyone have all permissions default group can use admin permissions and do everything.
Please help!

**Comment by BrainStone** [comment]
Check if LP is loading. If not be sure to update.

**Comment by BrainStone** [comment]
I take that as a "yes I just needed to update"

**Comment by M4rtyn4** [comment]
It's not update related. No clue why. Works fine when I start plugin with fresh files so will just set it up again from the beginning. Don't have time digging into it and was due to permission review anyway.

**Comment by BrainStone** [comment]
I see. Most likey it was fixed by deleting the libs folder inside the LP folder. The data not being relevant.
