### ISSUE TITLE
List of all permissions

### ISSUE THREAD

**Issue by renzotom** [lucko/LuckPermsWeb#4]
Can you add list of all permissions to the web intefrace of Luck Perms plugin?

Like it has Pex Builder plugin - https://www.spigotmc.org/resources/pexbuilder-gui.42248/ 

On that gift https://proxy.spigotmc.org/b3425bf1ae70ea9e335dc4624ec4cce370a93b5b?url=https%3A%2F%2Fgyazo.com%2Fea1a8474fbd796c151f158bc6c11c487.gif you can see, there is list of ALL permissions and you can simply drag them to active. Can you also make some like list of all permissions list and way to choose some from there and give there to a specific group?

**Comment by lucko** [comment]
Added by f39297d822d9821e77917cc26fc54fb237d0c483
