### ISSUE TITLE
Organize displayed groups by tracks

### ISSUE THREAD

**Issue by Rakdos8** [lucko/LuckPermsWeb#43]
It would be great to have tracks as a drop down list instead of the whole groups in random order.
That way, you can find out the group easly. If a group is not in a track, show it as usual but order by name (track first by name, then group by name).
The drop down list should also be ordered by hierarchy from the track

If you have 2 tracks with given groups:
1. Staff
    1. Visitor
    1. Player
    1. Modo
    1. Admin
1. VIP
    1. VIP
    1. VIP+
    1. MVP

It would be printed as 2 drop down list called "Staff" and "VIP" with their respective groups in the right order.
Meaning that Staff will have (top to bottom): Visitor, Player, Modo, Admin and VIP will have: VIP, VIP+, and MVP.

Thank you in advance :heart: !

**Comment by ricktolar** [comment]
Was just looking to see if this was possible.... Good suggestion!

**Comment by Turbotailz** [comment]
@lucko I can look into doing something like this but will need track data in the JSON response from bytebin

**Comment by lucko** [comment]
That's fine, can be easily added.

**Comment by Turbotailz** [comment]
Added in v2 (install LuckPerms v5 to use it).
