### ISSUE TITLE
Editor not working on Google Chrome

### ISSUE THREAD

**Issue by Rbot48** [lucko/LuckPermsWeb#45]
The following error is displayed in the console of the browser when trying to load the editor using Chrome Version 64.0.3282.186 (Official Build) (64-bit): 
![image](https://i.imgur.com/qXYg9rP.png)

The editor works without problems on other browsers, such as Edge and Firefox.

**Comment by lucko** [comment]
@BrainStone any ideas?

I haven't changed the checksum/version since we initially added jQuery

**Comment by ChineseMarc** [comment]
I saw this issue one more time and it was only there while some specific adblocker was enabled, i think that's problem here too

**Comment by BrainStone** [comment]
Yeah. It has been confirmed that an ad blocker was causing this.
