### ISSUE TITLE
Fixed position for editing panel

### ISSUE THREAD

**Issue by DardBrinza** [lucko/LuckPermsWeb#46]
Fix the specified panels for comfortable editing with too many permissions.

http://dl4.joxi.net/drive/2018/03/04/0002/2579/178707/07/dfd0f7cdfd.png

**Comment by lucko** [comment]
They're not meant to be lined up, if that's what you're asking.

I agree it'd be good if they stretched to fill the whole bar

**Comment by DardBrinza** [comment]
No, I ask to fix these panels when scrolling the page so that they do not move.
