### ISSUE TITLE
editor/tree/ verbose -> Own version

### ISSUE THREAD

**Issue by lastsamurai26** [lucko/LuckPermsWeb#47]
How can i use my own verion of  the newest version from the webeditor?

example 
Domain.de/ <- main folder
Domain.de/editor <- editor folder
Domain.de/tree <-  <- tree  folder
Domain.de/verbose  <- verbose  folder

i can only the editor when i add this line 
web-editor-url: "https://Domain.de/editor/"

how can i use the other stuff. i mean tree and verbose

**Comment by lucko** [comment]
The options are 

* `web-editor-url`
* `verbose-viewer-url`
* `tree-viewer-url`

Does that help? 🙂

**Comment by lastsamurai26** [comment]
:) thx can be closed 

i love it  :D
