### ISSUE TITLE
Side by side view

### ISSUE THREAD

**Issue by lucko** [lucko/LuckPermsWeb#50]
> Tabs: A feature where we can have two "group/user" tabs side by side for the web editor [This can be more than one if you want]   
Permission Dragging: To support the suggestion above, a feature where you can "drag" a permission from one group/user to another for convenience.

Taken from lucko/LuckPerms#916

**Comment by Turbotailz** [comment]
I'm not too keen on this idea. Reopen if you feel it should be added at some stage.
