### ISSUE TITLE
Permission selection for mass action

### ISSUE THREAD

**Issue by elstur** [lucko/LuckPermsWeb#54]
Basically, just a check box to the left of each permission to be able to select multiple permissions for actions such as:
- Delete
- toggle values (true/false, server, world, etc) all at once
- Copy to group (sometimes multiple groups use the same permissions in different ways)

**Comment by DonSensiLeone** [comment]
That would be such a great feature !

**Comment by Turbotailz** [comment]
Only took two years but it's finally here :)
