### ISSUE TITLE
Ability to drag or sort groups / users in WebEditor

### ISSUE THREAD

**Issue by ricktolar** [lucko/LuckPermsWeb#62]
Just a suggestion to add the ability to reorganize groups / users when we open a web session. I see that everything is currently listed by when the group was created (I was an idiot and created my mod group MUCH later and now it's buried in the middle of my groups).

**Comment by BrainStone** [comment]
If you give the groups weights, they are ordered by weight.

**Comment by ricktolar** [comment]
Seriously? How have I missed this? Trying now. Thanks for the heads up!
