### ISSUE TITLE
lp editor links from console

### ISSUE THREAD

**Issue by perpterds** [lucko/LuckPermsWeb#70]
I'm unsure if this belongs to LuckPerms or LuckPermsWeb, as I've no idea where the error actually is coming from. As such, I'm posting to the exact same message to both. By all means remove or notify me to remove as necessary :)

Running the command "lp editor" (or any alternate version, e.g. for group or user, et cetera) via console does generate a link as expected, but when copied and pasted to a web browser it's a 404 error.  I've already noticed that the link doesn't have the normal "?" after "editor/",  so I tried adding that, at which point it then gives the "incorrectly copied or session expired, please try again" page.

I've tried with a few different browsers, no change, and it's happened on two different servers, both running 4.3.8.  The command, and the link, work fine from in-game, on both servers.  Screenshots to follow.

https://snag.gy/qHgyQI.jpg
https://snag.gy/UubWck.jpg

**Comment by BrainStone** [comment]
This is a well known issues with MultiCraft.  
The current LP versions contain a workaround that fixes the issue.

**Comment by perpterds** [comment]
ah, didn't realize. i am using the most current downloadable (read: recommended) version from ore.  should i get a newer version from github then?

**Comment by BrainStone** [comment]
Yes. Recommended doesn’t mean much. All it means it is the recommended version that is uploaded to the ore page.

It isn’t updated that often so it’s always a good idea to check the official download page.

**Comment by perpterds** [comment]
duly noted, thank you for your help. closing :)
