### ISSUE TITLE
Show visual indicator for changed permissions

### ISSUE THREAD

**Issue by Andre601** [lucko/LuckPermsWeb#71]
The web-editor shows a little green line on the site of a permission if it was added through the editor.

A small issue, that could be annoying when editing large amounts of permissions is, that changed permissions (like for example changing `essentials.*` from `true` to `false`) don't have such a visual indicator and those changes could get lost when you edit a lot of them.

For that case it would be useful, to have a similar indicator like for adding a permission, just with another colour (an orange perhaps?)

**Comment by Andre601** [comment]
I close this since it seems that this was implemented.

**Comment by Turbotailz** [comment]
It's not perfect, though. It will still show as "modified" even if you put the node back to its original state.

**Comment by Andre601** [comment]
I honestly thought about mentioning exactly that.
That the node still shows as changed, even if you revert it.

**Comment by BrainStone** [comment]
I don't know how you're doing it right now, but just do a diff.  
All nodes you find that are in the current list of nodes and not in the original list of nodes are changed.

**Comment by Turbotailz** [comment]
> I don't know how you're doing it right now

I'm just toggling a boolean "modified" on each node/group if it's been updated. It's a pretty lazy approach and I was always going to improve it later on. I've not got any experience with diffs and can't seem to find a single good way to generate a diff for two objects. There are a few packages I could try that might work. I could always just JSON.stringify the initial data and the current data to see if the strings match.

A diff would be better, though.

**Comment by BrainStone** [comment]
I have literally explained how to make a diff that's good enough for that...

**Comment by Turbotailz** [comment]
> All nodes you find that are in the current list of nodes and not in the original list of nodes are changed.

And what about nodes that are still in the list but have been changed? It needs to go a bit deeper than that. But I will figure it out.

**Comment by BrainStone** [comment]
Detecting changed nodes is orders of maganitude more difficult. Just stick with modified/added and not modified/added. Computationinally that's O(n^2) and that's bad enough.  
And just to be sure we are talking about the same things:  
When I say "node" I mean the entirety of it. So permission, true/false, expiry, contexts.
