### ISSUE TITLE
Remove unnecessary whitespace in the permission field

### ISSUE THREAD

**Issue by Turbotailz** [lucko/LuckPermsWeb#72]
Some users will copy/paste permissions and may sometimes leave whitespace (spaces/tabs) at the end of them which then get added with the node. Use JS to strip extra whitespace on input blur.

**Comment by BrainStone** [comment]
This can run into issues with prefixes and suffixes. I think they need to be exempt.

**Comment by Turbotailz** [comment]
Yes, I was going to use `trim()` which only affects the beginning and end of a string and should not affect prefixes/suffixes with spaces.

**Comment by BrainStone** [comment]
Yes it will. As they can have intended trailing whitespace.

**Comment by Turbotailz** [comment]
I thought they had to be wrapped in quotes if they had spaces?

**Comment by BrainStone** [comment]
Only in the commands.

**Comment by Turbotailz** [comment]
Closing this in favour of #104
