### ISSUE TITLE
Readonly Editor

### ISSUE THREAD

**Issue by Foxtrek64** [lucko/LuckPermsWeb#76]
This may rely on some changes @Turbotailz mentioned he had planned, and it will also rely on a sister issue in the [lucko/LuckPerms](https://github.com/lucko/LuckPerms/) repo.

For `/lp editor` and sister commands, we should be able to provide a `readonly` flag to the end of the command line. This should give us a link we can share publicly for those who wish to diagnose permission issues but without giving them control to edit the permissions.

On the web editor end, I imagine this change would simply involve removing and disabling a few components for the readonly version, though having not explored the codebase I'm not entirely sure what that would look like.

**Comment by Turbotailz** [comment]
> it will also rely on a sister issue in the [lucko/LuckPerms](https://github.com/lucko/LuckPerms/) repo.

Which issue are you referring to?

Anyway the web editor is read only until the `/applyedits` command is run on the server. If someone has access to an editor URL there is no risk involved unless they somehow gain access to run `/applyedits` on the originating server.

I do believe you can just run an `/applyedits` command on any server, not just the one where the session originated from. That can possibly be an issue, but really, if anyone does and adds a bunch of random permissions to their server, then it's their own fault. I'm sure Luck could put something in place plugin-side that could prevent this from happening but we just haven't heard of any cases where this is an issue.

I could do some like adding a parameter to the URL like `/editor/<code>?r=1` which could render the editor without the editable regions but that won't stop anyone from just removing the parameter to enable it to be editable.

Happy to talk about this more and see what we can come up with though.

**Comment by Foxtrek64** [comment]
This was a mistake on my part. I'd had it in my mind that clicking the save button would push the changes to the server, though I forgot that this process required the `/applyedits` step. Makes the readonly parameter seem like a moot point.
