### ISSUE TITLE
Add from list

### ISSUE THREAD

**Issue by xAphex** [lucko/LuckPermsWeb#78]
Can you please add an option to "add from list" so we can paste a whole list of perms to the web editor and it adds them separately?

List of perms like this:

- essentials.exp.give
- essentials.exp.set
- essentials.ext
- essentials.feed
- essentials.fly
- essentials.gamemode
- essentials.gamemode.all
- essentials.gc
- essentials.getpos
- essentials.give
- essentials.hat
- essentials.heal
- essentials.help
- essentials.helpop
- essentials.home.bed
- essentials.home.compass
- essentials.ignore
- essentials.info
- essentials.item
- essentials.itemdb
- essentials.itemspawn.meta-book

You copy it and then paste it in web editor and web editor will add them in separate boxes where you can add world, change expiry date, restrict to certain server.. etc

Or you can browse from a .txt file on the computer.

**Comment by Andre601** [comment]
There is a rework of the editor currently being made, but it will take its time.
Having support to mass-add permissions from file is a planned thing.
