### ISSUE TITLE
Issue self-hosting luckperms editor/verbose etc

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [lucko/LuckPermsWeb#79]
All is working, the game directs me to my hosted interface etc. 
Clicking the link to open the editor/verbose/tree takes me to my webpage.
After that, I get this message. 
![screengrabber_03032019_224216](https://user-images.githubusercontent.com/40422890/53693497-2b60c980-3e06-11e9-8e32-24f49668b10d.png)

No errors/messages are shown in the server console.

Luckperms v4.3.99
Spigot server 

Was taking with BrainStone on the Discord server and we couldn't figure it out.

**Comment by lucko** [comment]
Most likely an issue with your webserver. What are you using?

**Comment by nzminecraftDOTcom** [comment]
Using Apache

**Comment by TRose2000** [comment]
works fine for me^

**Comment by nzminecraftDOTcom** [comment]
@TRose2000 That's not really helpful if I'm honest with you. Would you mind sharing what you did to make it run with Apache?

**Comment by TRose2000** [comment]
@nzminecraftDOTcom ur missing the directory `assets`

**Comment by nzminecraftDOTcom** [comment]
The assets directory in the editor, verbose and tree folders containing the two files named app.js and style.css?
I have those.

**Comment by TRose2000** [comment]
In your main root folder
Before you open editor/verbose/tree

**Comment by nzminecraftDOTcom** [comment]
What do I need in that assets folder?

**Comment by Turbotailz** [comment]
I'm going to close this as it seems more like a problem with your particular setup and it's been open for a while with no resolution. You can open it again if you need but you may as well wait until v2 is complete.
