### ISSUE TITLE
Drag and Drop Permission nodes between groups to other "tabs"

### ISSUE THREAD

**Issue by i9hdkill** [lucko/LuckPermsWeb#86]
So we finally started to migrate our servers to use one single mariadb, away from tons of lp instances with yamls backends.
As this was a big change anyway, I started to move around some group permissions. But I had to click copy on them individually, go to the other group tab and click paste.

What about a small handle that indicates you can grab a permission and drag it onto a group or user tab to automatically move it to that destination when releasing the mouse button.
![Download22](https://user-images.githubusercontent.com/4679374/57739511-29dc3900-76b4-11e9-9565-4e3398fe0b19.jpg)

**Comment by Turbotailz** [comment]
I've added the ability to copy/move permissions. It's not drag and drop but will offer the same functionality.
