### ISSUE TITLE
How do i fix this

### ISSUE THREAD

**Issue by BootlegCenny** [lucko/LuckPermsWeb#87]
![image](https://user-images.githubusercontent.com/49611200/58374129-db8f2b80-7f38-11e9-80d9-302a5e62d7ec.png)

How to i make the second [*] dissapear?

Plugins that might conflict is the towny plugin.

Anyways please help ;I

**Comment by BrainStone** [comment]
First of all, this not the LuckPerms repository. Second LuckPerms is not responsible for displaying your prefixes, etc. That's entirely up to your chat plugin. Check their docs and ask for help on their support channels.
