### ISSUE TITLE
Better understanding of LuckPerms

### ISSUE THREAD

**Issue by MrKiller01** [lucko/LuckPermsWeb#88]
I have an issue stepping from PermissionsEx to LuckPerms.
As the way of changing PEX through a dashboard (even online) that was so 2019+, I felt a bit of backwards when doing it through IMPORT and EXPORT (Gave an error when importing a file that was exported without changing a thing) and the EDIT function is too hazy, too clouded.
When PEX was needed to be active before even begin migration, all hell broke loose when I removed PEX from the server equation. Something babbling about missing permissions etc. etc...
Is this normal?

So my question to you is, can you make a more easy to use GUI so that perms are more easy to change?

**Comment by Andre601** [comment]
There is an entire wiki page about switching (migrating) from PEX to LuckPerms, but it is as simple as follows:
1. Have the PEX and LP jar on the server.
2. Run `/lp migrate PermissionsEx`
3. Check console for any errors.

The export and import command are for making and loading backups and for switching storage types.
Also there is a web editor for easy editing of perms.

**Comment by MrKiller01** [comment]
Sorry, but my suggestion, is that in the right place? bet you say not....

**Comment by BrainStone** [comment]
This is the right place: https://github.com/lucko/LuckPerms  
And yeah. Migrating from PEX really isn't hard.
