### ISSUE TITLE
[v2] Scrolling down in group editor breaks group name header

### ISSUE THREAD

**Issue by upstreamsea** [lucko/LuckPermsWeb#96]
Device: Mac Book Pro 2018 15"

Browser: Safari

Issue: Scrolling down while in a web editor view will break the header for the group name. Please see attached images.

<img width="1396" alt="Screen Shot 2019-11-23 at 1 36 45 PM" src="https://user-images.githubusercontent.com/55110037/69484207-5fe23e80-0df6-11ea-9133-428f99e850f0.png">
<img width="1393" alt="Screen Shot 2019-11-23 at 1 36 58 PM" src="https://user-images.githubusercontent.com/55110037/69484208-607ad500-0df6-11ea-8fef-18ad0a7c96cf.png">
<img width="1393" alt="Screen Shot 2019-11-23 at 1 37 08 PM" src="https://user-images.githubusercontent.com/55110037/69484209-607ad500-0df6-11ea-8fab-2c6e67d755bd.png">

**Comment by upstreamsea** [comment]
Will be testing with Chrome, Firefox, or Opera once on stable wifi to download additional browsers.

**Comment by upstreamsea** [comment]
Closing. Accidentally posted this on LuckPerms instead of LuckPermsWeb.

**Comment by upstreamsea** [comment]
Can't replicate on Chrome or Firefox on the same device.

Issue seems to just impact Safari.

**Comment by BrainStone** [comment]
I imagine debugging this will be hard as Safari is no longer available for Windows.
